<h1><?= $this->type; ?> Management</h1>
<div class="row breadcrumb-wrapper">
	<div class="col-sm-12">
		<ol class="breadcrumb">
			<li><a href="#">Home</a></li>
			<li><a href="/admin/users">Users</a></li>
			<li class="active">Edit</li>
		</ol>	
	</div>
</div>
<br/>
<?php
$form->setAttribute('action', '/admin/user/edit/' . $this->id);
$form->prepare();
?>

<?= $form ?>

<script>
    $(document).ready(function(){
        userEdit.init();
    });
</script>			