<h1><?= $this->type; ?> Management</h1>
<div class="row breadcrumb-wrapper">
	<div class="col-sm-8">
		<ol class="breadcrumb">
			<li><a href="/admin">Home</a></li>
			<li class="active"><?= $this->type; ?>s</li>
		</ol>	
	</div>
	<div class="col-sm-4">
		<a class="btn btn-default admin-btn pull-right" href="<?= $this->url('admin-' . strtolower($this->type) . '-add'); ?>">Add <?= $this->type; ?></a>
	</div>
</div>
<br/>
<div class="row" id="admin-search">
	<div class="col-sm-12">
		<div class="container">
			<div class="row">
				<div class="col-sm-12"><b>Search <?= $this->type; ?>s</b></div>
			</div>
			<div class="row">
				<div class="col-sm-3">
					<label>UserName</label><br/>
					<input id="search-username" type="text" placeholder="UserName" class="col-sm-12 typeahead">
				</div>
				<div class="col-sm-2">
					<label>State</label>
					<select id="search-province" data-ref="State" data-target="search-city" class="col-sm-12">
						<option value="">All</option>
<?php foreach ($this->provinces as $province) { ?>
						<option value="<?= $province['id']; ?>"><?= $province['name']; ?></option>
<?php } ?>
					</select>
				</div>
				<div class="col-sm-3">
					<label>City</label>
					<select id="search-city" data-ref="City" class="col-sm-12" disabled="disabled">
						<option value="">All</option>
					</select>
				</div>
				<div class="col-sm-2">
					<label>Added On or After</label>
					<input id="search-created-after" type="text" class="col-sm-8 datefield"></i>
				</div>
				<div class="col-sm-2">
					<label>Added On or Before</label>
					<input id="search-created-before" type="text" class="col-sm-8 datefield"></i>
				</div>
			</div>
<?php if ($type == 'User') { ?>			
			<div class="row">
				<div class="col-sm-12 pull-right">
					<label>Role</label><br />
					<select id="search-status">
						<option value="">All</option>
						<option value="User">Users</option>
						<option value="Artist">Artists</option>
						<option value="Administrator">Administrators</option>
						<option value="Unconfirmed">Unverfied Users</option>
					</select>
				</div>
			</div>
<?php } ?>			
		</div>
	</div>
</div>
<div class="row">
	<div class="col-sm-12" id="record-list-wrapper">
		<table id="record-list-results">
			<thead>
				<tr>
				<th class="check-field"></th>
				<th class="active id-field">Id <i id="admin-sort-id" class="icon-admin-sort icon-admin-sort-up"></i></th>
				<th class="username-field">Username <i id="admin-sort-username" class="icon-admin-sort icon-admin-sort-undefined"></i></th>
				<th class="name-field">Name <i id="admin-sort-name" class="icon-admin-sort icon-admin-sort-undefined"></i></th>
				<th class="email-field">Email <i id="admin-sort-email" class="icon-admin-sort icon-admin-sort-undefined"></i></th>
				<th class="location-field">Location <i id="admin-sort-location" class="icon-admin-sort icon-admin-sort-undefined"></i></th>
				<th class="joined-field">Joined <i id="admin-sort-joined" class="icon-admin-sort icon-admin-sort-undefined"></i></th>
				<th class="status-field">Role <i id="admin-sort-status" class="icon-admin-sort icon-admin-sort-undefined"></i></th>
				<th class="actions-field">Actions</th>
				</tr>
			</thead>
			<tbody>
			</tbody>
		</table>
	</div>
</div>
<script src="/js/userSearch.js" type="text/javascript"></script>
<script>
<?php if ($this->status !== null) { ?>
$('#search-status').val('<?= $this->status; ?>');
<?php } ?>
$().userSearch({
	type: '<?= $this->type; ?>'
});
</script>
