<div class="container" id="videoUpload">
    <?php foreach ($flash as $f): ?>
        <div class="alert alert-success" role="alert" style="display:block;"><?= $f ?></div>
    <?php endforeach; ?>
    <div class="row col-md-10 col-md-offset-1">

        <div class="col-sm-12">
            <h2>Edit a Video</h2>
            <?= $headForm ?>
        </div>


        <div class="col-md-8">
            <?= $mainForm ?>
        </div>
        <div class="col-md-4">
            <?= $videoMediaForm ?>
        </div>


        <div class="row">
            <div class="row">
                <div class="col-md-10 col-md-offset-1 form-group">
                    <form id="submitForm" action="/videos/edit/<?= $data['id'] ?>" method="POST">
                        <button id="submit" class="form-control btn btn-primary" type="submit">Submit Video</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <script>
        upload.init();
    </script>
