<form id="fbVideosForm" class="row" action="/videos/review-fb" method="post">
	<div class="col-md-8">
		Please click on the video(s) you want to upload to TownSpot, then click the "Continue" button,
		where you will be able modify the titles and descriptions for each video
	</div>

	<div id="pick-videos" class="row">
		<?php foreach($videos as $v): ?>
	  <div class="media col-md-6">
		<?php $wrapperClass = (empty($v['in_system']))? ' panel panel-default' : ' well'; ?>
		  <div class="wrapper col-md-12<?= $wrapperClass ?>" data-id="<?= $v['id'] ?>">
			<div class="media-left col-md-6" style="background-image: url(<?= $v['picture'] ?>);">
				<!-- <img class="media-object img-responsive" src="<?= $v['picture'] ?>" alt="<?= $v['title'] ?>"> -->
			</div>
			<div class="media-body col-md-6">
			  <h4 class="media-heading"><?= $v['title']? $v['title']: 'Untitled Video' ?> - <?= ceil($v['length']) ?> seconds</h4>
			  <?= substr(strip_tags($v['description']),0,100) ?><?= (strlen(strip_tags($v['description'])) > 100)? '...':'' ?>
			</div>
		  </div>
	  </div>
	  <?php endforeach; ?>
	</div>
	<button id="submit-videos" class="btn btn-primary col-md-12 btn-lg">Continue</button>
</form>