<?php
$artist = $this->media->getUser();
$artistName = $artist->getDisplayName();
?>
<div class="container video-player">
    <div class="row">
        <div class="col-xs-12">
            <div class="media">
                <?= $this->VideoPlayer(
                    $this->media,
                    array(
                        'width' => '100%',
                        'preview_width' => 800,
                        'preview_height' => 450,
                        'include_info' => true,
                    )
                ); ?>
            </div>
        </div>
    </div>
</div>