<div class="container video-player">
	<div class="row">
		<div class="col-xs-12">
			<div class="media">
                <?php if($this->media->getSource() == 'vimeo') :
                    preg_match("/\/([0-9]+)/",$this->media->getUrl(),$matches);
                    $id = $matches[1];
                ?>
                    <iframe class="vimeoPlayer" src="https://player.vimeo.com/video/<?= $id ?>?api=1" frameborder="0"></iframe>
                <?php else : ?>
				<?= $this->VideoPlayer(
					$this->media,
					array(
						'width' => '100%',
						'preview_width' => 800,
						'preview_height' => 450,
						'include_sharing' => true,
						'include_related' => true,
						'include_info' => true,
						'include_buttons' => true,
					)
				); ?>
                <?php endif; ?>
			</div>
		</div>
	</div>
	<div class="row video-info">
		<div class="col-sm-8">
			<div class="row">
				<div class="col-xs-12">
					<h3>Description</h3>
					<div class="expandable">
						<?= $this->media->getDescription(); ?>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-xxs-5 col-xs-4 col-sm-3">
					<h3>Location:</h3>
				</div>
				<div class="col-xxs-7 col-xs-8 col-sm-9">
					<ul class="boxed-list">
						<li><a href="<?= $this->media->getCity()->getDiscoverLink(); ?>"><?= $this->media->getCity()->getName(); ?></a></li>
						<li><a href="<?= $this->media->getProvince()->getDiscoverLink(); ?>"><?= $this->media->getProvince()->getName(); ?></a></li>
					</ul>
				</div>
			</div>
			<div class="row">
				<div class="col-xxs-5 col-xs-4 col-sm-3">
					<h3>Genres:</h3>
				</div>
				<div class="col-xxs-7 col-xs-8 col-sm-9">
					<ul class="boxed-list genres">
<?php foreach ($this->media->getCategories() as $category) { ?>
						<li><a href="<?= $category->getDiscoverLink(); ?>"><?= $category->getName(); ?></a></li>
<?php } ?>							
					</ul>
				</div>
			</div>
			<div class="row">
				<div class="col-xs-12 social-media_wrapper">
<?= $this->AddThisLinks($this->serverUrl(true));  ?>				
				</div>
			</div>
			<div class="row comments-row">
				<div class="col-xs-12">
					<div class="col-xxs-5 col-xs-4 col-sm-3 comments-header">
						<h3>Comments:</h3>
					</div>
				</div>
				<div class="row form-group">
					<div class="col-xs-9 nopadding-right full-320">
						<input type="text" class="col-sm-8 form-control" placeholder="Leave a Comment" id="comment-field">
					</div>
					<div class="col-xs-3 nopadding-left full-320">
						<button class="form-control btn interaction-button" id="comment-submit">Comment</button>
					</div>
				</div>	
				<div class="row">
					<div class="col-sm-12">
						<div class="alert alert-block alert-error" id="comment-error">
							<button type="button" class="close" data-dismiss="alert">X</button>
							<h4 class="alert-heading"></h4>
							<p class="alert-body"></p>
						</div>	
					</div>	
				</div>	
				<div class="row">
					<div class="col-sm-12" id="comments">
						<ul id="comment-list">
						</ul>
					</div>
				</div>
				<div class="row">
					<div class="col-sm-12">
						<div id="comment-navigation-down" style="display: none;"><button class="btn btn-default next col-xs-12"><i class="fa fa-chevron-down"></i></button></div>
					</div>
				</div>
			</div>
		</div>
		<div class="col-sm-4">
			<h3>Similar Videos</h3>
			<ul id="matching-videos" class="matching-videos">
<?php foreach ($this->related as $related_video) { ?>
				<li><?= $this->VideoBlock($related_video,false); ?></li>
<?php } ?>			
			</ul>
		<?= $this->VideoCarousel($this->related,array(
			'id' => 'matching-videos-xs',
			'per_panel' => 3,
			)); ?>
			
		</div>
	</div>
</div>

<div class="modal fade" id="FlagContentModal" tabindex="-1" role="dialog" aria-labelledby="FlagContentLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">x</button>
				<h4 class="modal-title" id="FlagContentLabel">Flag for Review</h4>
			</div>
			<div class="modal-body">
				<label>Reason</label>
				<select id="flag-reason" class="form-control">
					<option>Inappropriate Content</option>
					<option>Copyright Infringement</option>
				</select>
				<label>Your Name</label>
				<input id="flag-name" type="text" placeholder="Please enter your name" class="form-control">
				<div id="name-error" class="alert alert-block alert-error">
					<button data-dismiss="alert" class="close" type="button">x</button>
					<h4 class="alert-heading"></h4>
					<p class="alert-body"></p>
				</div>
				<label>Your Email</label>
				<input id="flag-email" type="text" placeholder="Please enter your email" class="form-control">
				<div id="email-error" class="alert alert-block alert-error">
					<button data-dismiss="alert" class="close" type="button">x</button>
					<h4 class="alert-heading"></h4>
					<p class="alert-body"></p>
				</div>
				<label>Message</label>
				<textarea placeholder="Please state reason for flagging video" id="flag-message" class="form-control"></textarea>
				<div id="flag-error" class="alert alert-block alert-error">
					<button data-dismiss="alert" class="close" type="button">x</button>
					<h4 class="alert-heading"></h4>
					<p class="alert-body"></p>
				</div>
			</div>
			<div class="modal-footer">
				<button value="Request Review" id="flag-submit" class="btn btn-primary btn-large">Request Review</button>
			</div>
			<div id="success-message" class="alert alert-success">
				<button data-dismiss="alert" class="close" type="button">x</button>
				<h4 class="alert-heading"></h4>
				<p class="alert-body"></p>
			</div>
		</div>
	</div>
</div>

<div class="modal fade" id="ContactCreatorModal" tabindex="-1" role="dialog" aria-labelledby="ContactCreatorLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">x</button>
				<h4 class="modal-title" id="ContactCreatorLabel">Contact Video Creator</h4>
			</div>
			<div class="modal-body">
				<label>Subject</label>
				<input id="contact-subject" type="text" placeholder="Please enter a subject" class="form-control">
				<div id="contact-error-subject" class="alert alert-block alert-error">
					<button data-dismiss="alert" class="close" type="button">x</button>
					<h4 class="alert-heading"></h4>
					<p class="alert-body"></p>
				</div>
				<label>Message</label>
				<textarea placeholder="Please enter a message" id="contact-message" class="form-control"></textarea>
				<div id="contact-error" class="alert alert-block alert-error">
					<button data-dismiss="alert" class="close" type="button">x</button>
					<h4 class="alert-heading"></h4>
					<p class="alert-body"></p>
				</div>
			</div>
			<div class="modal-footer">
				<button value="Send" id="contact-submit" class="btn btn-primary btn-large">Send</button>
			</div>
			<div id="message-success-message" class="alert alert-success">
				<button data-dismiss="alert" class="close" type="button">x</button>
				<h4 class="alert-heading"></h4>
				<p class="alert-body"></p>
			</div>
		</div>
	</div>
</div>

<div class="modal fade" id="ArtistContactModal" tabindex="-1" role="dialog" aria-labelledby="ArtistContactLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">x</button>
				<h4 class="modal-title" id="ArtistContactLabel">Allow Artist to Contact Me</h4>
			</div>
			<div class="modal-body">
				<table>
					<tr>
						<td><button id="artist-contact-yes" class="btn btn-success btn-large">Yes</button></td>
						<td><button id="artist-contact-no" class="btn btn-danger btn-large">No</button></td>
					</tr>
				</table>
			</div>
		</div>
	</div>
</div>

<div class="modal fade" id="SetupError" tabindex="-1" role="dialog" aria-labelledby="SetupLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">x</button>
				<h4 class="modal-title" id="SetUpLabel">An Error has occurred</h4>
			</div>
			<div class="modal-body" id="SetupErrorMessage">
			</div>
		</div>
	</div>
</div>
<div class="row ad-panel">
	<div class="col-xs-12">
		<div class="col-xs-12 google-ad" data-position="leaderboard" ></div>
	</div>
</div>

<script>
$().Interactions({
	videoid: <?= $this->media->getId(); ?>,
	userid: <?= ($this->zfcUserIdentity()) ? $this->zfcUserIdentity()->getId() : 0; ?>
});
setInfoButtons();
</script>
