<div id="review-videos" class="row">
    <form id="reviewForm" action="/videos/submit/<?= $source ?>" method="post" class="col-md-12">
        <div class="row col-md-12">
            <div class="col-md-8">Please provide a title & description for each video, then hit the "Submit" button</div>
        </div>
        <div class="row col-md-12">
        <?php foreach ($videos as $v): ?>
            <div class="media col-md-12 well">
                <div class="media-left col-md-4" style="background-image: url(<?= $v['thumbnail'] ?>);">
                </div>
                <div class="media-body col-md-8">
                    <div class="form-group">
                        <label for="title" class="required">Title</label>
                        <input type="text" class="title form-control" value="<?= $v['title'] ?>"
                               name="data[<?= $v['id'] ?>][title]">
                    </div>
                    <div class="form-group">
                        <label for="description" class="required">Description</label>
                        <textarea class="description form-control" value="<?= $v['description'] ?>"
                               name="data[<?= $v['id'] ?>][description]"><?= $v['description'] ?></textarea>
                    </div>

                    <input type="hidden" class="url" value="<?= $v['url'] ?>"
                           name="data[<?= $v['id'] ?>][url]">
                    <input type="hidden" class="source" value="<?= $source ?>"
                           name="data[<?= $v['id'] ?>][source]">
                    <input type="hidden" class="duration" value="<?= $v['duration'] ?>"
                           name="data[<?= $v['id'] ?>][duration]">
                    <input type="hidden" class="thumbnail" value="<?= $v['thumbnail'] ?>"
                           name="data[<?= $v['id'] ?>][thumbnail]">
                    <input type="hidden" class="country_id" value=""
                           name="data[<?= $v['id'] ?>][country_id]">
                    <input type="hidden" class="province_id" value=""
                           name="data[<?= $v['id'] ?>][province_id]">
                    <input type="hidden" class="city_id" value=""
                           name="data[<?= $v['id'] ?>][city_id]">
                    <input type="hidden" class="allow_contact" value=""
                           name="data[<?= $v['id'] ?>][allow_contact]">
                    <input type="hidden" class="authorised" value=""
                           name="data[<?= $v['id'] ?>][authorised]">
                </div>
            </div>
        <?php endforeach; ?>
            <div class="row col-md-12">
                <div class="col-md-8">&nbsp;</div>
                <button id="submit-videos" class="btn btn-primary btn-lg col-md-12">Submit</button>
            </div>
        </div>
    </form>
</div>

<script>
    function getStates($parent){
        $parent.find('.province_id option:not(:first)').remove();
        $parent.find('.province_id option:first').text('loading...');
        $parent.find('.city_id option:not(:first)').remove();
        $parent.find('.city_id option:first').text('loading...');
        $.get(
            '/api/province/getList/' +  $parent.find('.country_id').val(),
            function(response){
                var data = response.data;
                if(data.length) {
                    $parent.find('.province_id option:first').text('Please Select a State');
                    $(data).each(function(){
                        $parent.find('.province_id').append("<option value='"+ this.id +"'>"+ this.name +"</option>");
                    });
                    $parent.find('.city_id option:first').text('Please Select a State');
                    $parent.find('.province_id, .city_id, [for=province_id], [for=city_id]').show();
                } else {
                    $parent.find('.province_id, #city_id, [for=province_id], [for=city_id]').hide();
                }
            }
        );
    }
    function getCities($parent) {
        $parent.find('.city_id option:not(:first)').remove();
        $parent.find('.city_id option:first').text('loading...');
        $.get(
            '/api/city/getList/' +  $parent.find('.province_id').val(),
            function (response) {
                var data = response.data;
                if (data.length) {
                    $parent.find('.city_id option:first').text('Please Select a City');
                    $(data).each(function () {
                        $parent.find('.city_id').append("<option value='" + this.id + "'>" + this.name + "</option>");
                    });
                    $parent.find('.city_id option:first').text('Please Select a City');
                    $parent.find('.city_id').show();
                } else {
                    $parent.find('.city_id option:first').text('Not Applicable');
                }
            }
        );
    }

    function validate_fb() {
        $('.formError').removeClass('.formError');
        var val_error = false;
        $('label.required + input, label.required + textarea, label.required + select, label.required > input').each(function(){
            var $this = $(this);
            console.log($this);
            var error = false;
            if($this.is('input,textarea') && $this.val().length == 0) {
                error = true;
            } else if($this.is('select') && ($this.val() == 0 || $this.val() == '' || $this.val() == undefined)) {
                error = true;
            } else if($this.is('[type=checkbox]') && !$this.is(':checked')) {
                //custom error stuff
                $this.parent().addClass('formError');
            }

            if(error) {
                $this.addClass('formError');
                val_error = true;
            }
        });

        return !val_error;
    }
    $(document).ready(function(){
        $('.country_id').val(localStorage.getItem('countryId'));
        $('.province_id').val(localStorage.getItem('provinceId'));
        $('.city_id').val(localStorage.getItem('cityId'));
        $('.authorised').val(localStorage.getItem('authorised'));
        $('.allow_contact').val(localStorage.getItem('allowContact'));
    });
</script>