<div class="container" id="videoUpload">
    <div class="row">
        <div class="col-md-12 row">
            <div class="col-sm-12">
                <h2>Submit a Video</h2>
            </div>
            <?= $headForm ?>
        </div>
        <div class="row">
            <div class="col-sm-12">
                <ul id="uploadTabs" class="nav nav-tabs nav-justified">
                    <li id="youtab" class="active">
                        <a href="#youtube" data-toggle="tab">Submit Via <img class="youtubelogo" src='/img/youtube.png' alt="youtube"></a>
                    </li>
                    <li id="vimtab"><a href="#vimeo" data-toggle="tab">Submit via <img class="vimeologo" src='/img/vimeo.png' alt="youtube"></a></li>
                    <li id="dmtab"><a href="#dailymotion" data-toggle="tab">Submit via <img class="dmlogo" src='/img/dailymotion.png' alt="youtube"></a></li>
                    <li id="fbtab"><a href="#facebook" data-toggle="tab">Submit via <img class="fblogo" src='/img/fb.png' alt="facebook"></a></a></li>
                    <li><a href="#upload" data-toggle="tab">Submit via Upload</a></li>
                </ul>
            </div>
        </div>
        <div class="tab-content">
            <div id="upload" class="tab-pane">
                <div class="col-md-8">
                    <?= $manualForm ?>
                </div>
                <div class="col-md-4">
                    <?= $videoMediaForm ?>
                </div>
                <div class="col-md-12">
                    <form id="submitForm" action="/videos/review" method="POST" style="display:none;">
                        <button id="submit" class="form-control btn btn-primary" type="submit">Submit Video</button>
                    </form>
                </div>

            </div>
            <div class="tab-pane  active" id="youtube">
                <h3 class="uploadLogo"><img class="youtubelogo" src="/img/youtube.png" alt="youtube"> Submission</h3>
                <p>Click the button below to select which of your Youtube videos you would like to show on Townspot</p>
                <a href="/videos/youtube-videos" class="btn btn-primary btn-lg col-md-12 selectVideos">Select Videos</a>
            </div>
            <div class="tab-pane" id="vimeo">
                <h3 class="uploadLogo"><img class="vimeologo" src='/img/vimeo.png' alt="vimeo"> Submission</h3>
                <p>Click the button below to select which of your Vimeo videos you would like to show on Townspot</p>
                <a href="/videos/vimeo-videos" class="btn btn-primary btn-lg col-md-12 selectVideos">Select Videos</a>
            </div>
            <div class="tab-pane" id="facebook">
                <h3 class="uploadLogo"><img class="fblogo" src='/img/fb.png' alt="Facebook"> Submission</h3>
                <p>Click the button below to select which of your Facebook videos you would like to show on Townspot</p>
                <a href="/videos/fb-videos" class="btn btn-primary btn-lg col-md-12 selectVideos">Select Videos</a>
            </div>
            <div class="tab-pane" id="dailymotion">
                <h3 class="uploadLogo"><img class="dmlogo" src='/img/dailymotion.png' alt="Daily Motion"> Submission</h3>
                <p>Click the button below to select which of your Dailymotion videos you would like to show on Townspot</p>
                <a href="/videos/dailymotion-videos" class="btn btn-primary btn-lg col-md-12 selectVideos">Select Videos</a>
            </div>
        </div>
    </div>
    <div class="modal fade" id="resultModal">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title">Your video Upload...</h4>
                </div>
                <div class="modal-body">
                    <p class="content"></p>
                </div>
            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->
    <script>
        upload.init();
    </script>
