<div class='hidden'>
	<?php var_dump($in_system); ?>
</div>
<form id="ytVideosForm" class="row" action="/videos/review-yt" method="post">
	<div class="col-md-8">
		Please click on the video(s) you want to upload to TownSpot, then click the "Continue" button,
		where you will be able modify the titles and descriptions for each video
	</div>

	<div id="pick-videos" class="row">
	<?php foreach($videos as $i =>  $v): ?>
	  <div class="media col-md-6">
<div class='hidden'>
        <?php var_dump($in_system,  in_array($i, $in_system)); ?>
</div>
		<?php $wrapperClass = !in_array($i, $in_system)? ' panel panel-default' : ' well'; ?>
		  <div class="wrapper col-md-12<?= $wrapperClass ?>" data-id="<?= $v->getId() ?>">
			<div class="media-left col-md-6" style="background-image: url(<?= $v->getSnippet()['thumbnails']['high']['url'] ?>);">
				&nbsp;
			</div>
			<div class="media-body col-md-6">
				<?php
					$duration = $v->getContentDetails()['duration'];
					preg_match('/(\d*)H/',$duration,$h);
					preg_match('/(\d*)M/',$duration,$m);
					preg_match('/(\d*)S/',$duration,$s);

					if(count($h)) $h = $h[1] * 60 * 60;
					if(count($m)) $m = $m[1] * 60;
					if(count($s)) $s = $s[1];

					$duration = intval($h) + intval($m) + intval($s);
				?>
			  <h4 class="media-heading"><?= $v->getSnippet()['title']? $v->getSnippet()['title']: 'Untitled Video' ?> - <?= $duration ?> seconds</h4>
			  <?= substr(strip_tags($v->getSnippet()['description']),0,100) ?><?= (strlen(strip_tags($v->getSnippet()['description'])) > 100)? '...':'' ?>
			</div>
		  </div>
	  </div>
  	<?php endforeach; ?>
	</div>
	<button id="submit-videos" class="btn btn-primary col-md-12 btn-lg">Continue</button>
</form>
