<?php echo $this->doctype(); ?>
<html>
	<head>
        <meta charset="utf-8">
        <?= $this->headTitle('Townspot Admin')->setAutoEscape(false) ?>
        <?= $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0');	?>
        <?= $this->headMeta()->appendHttpEquiv('X-UA-Compatible', 'IE=edge'); ?>
        <?= $this->headLink(array(	'rel' => 'shortcut icon', 
									'type' => 'image/vnd.microsoft.icon', 
									'href' => $this->basePath() . '/img/favicon.ico'
			));
		?>
		<link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">		
		<link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap-theme.min.css">
		<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
		<link href="//code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" rel="stylesheet" type="text/css">
        <?= $this->headLink()->prependStylesheet($this->basePath() . '/css/admin.css'); ?>
		<script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
		<script type="text/javascript" src="http://bp.yahooapis.com/2.4.21/browserplus-min.js"></script>
		<script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
		<script type="text/javascript" src="http://malsup.github.com/jquery.form.js"></script>
		<script type="text/javascript" src="//code.jquery.com/ui/1.10.2/jquery-ui.js"></script>
		<script type="text/javascript" src="//ajax.aspnetcdn.com/ajax/jquery.validate/1.11.1/jquery.validate.js"></script>
		<script type="text/javascript" src="//jwpsrv.com/library/y3klzqiFEeKGEyIACpYGxA.js"></script>
        <?= $this->headScript()->appendFile($this->basePath() . '/js/admin.js'); ?>
	</head>
	<body>
		<div class="container">
			<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
				<div class="container">
					<ul class="nav navbar-nav">
						<li><a href="<?= $this->url('admin-home'); ?>" id="home" ><i class="fa fa-home"></i>&nbsp;Home</a></li>
					</ul>
					<ul class="nav navbar-nav navbar-right">
						<li><a href="<?= $this->url('home'); ?>">EXIT ADMIN</a></li>
						<li><a href="<?= $this->url('logout'); ?>"><i class="fa fa-power-off"></i>&nbsp;LOGOUT</a></li>
					</ul>
				</div>
			</nav>
		</div>
		<br/>
		<br/>
		<br/>
		<div class="container">
			<nav class="navbar" role="navigation">
				<div class="container-fluid">
					<ul class="nav nav-tabs" id="admin-tab">
						<li>
							<div class="btn-group">
								<a href="<?= $this->url('admin-home'); ?>" class="btn admin-btn btn-inverse"><i class="fa fa-dashboard"></i> Dashboard</a>
							</div>
						</li>
						<li class="dropdown">
							<div class="btn-group">
								<a href="<?= $this->url('admin-artists'); ?>" class="btn btn-info admin-btn dropdown-toggle"><i class="fa fa-group"></i> Artists&nbsp;<i class="fa fa-caret-square-o-down"></i></a>
								<ul class="dropdown-menu">
									<li><a href="<?= $this->url('admin-artist-add'); ?>"><i class="fa fa-user"></i> Add Artist</a></li>
								</ul>
							</div>
						</li>
						<li class="dropdown">
							<div class="btn-group">
								<a href="<?= $this->url('admin-users'); ?>" class="btn btn-info admin-btn dropdown-toggle"><i class="fa fa-group"></i> Users&nbsp;<i class="fa fa-caret-square-o-down"></i></a>
								<ul class="dropdown-menu">
									<li><a href="<?= $this->url('admin-user-add'); ?>"><i class="fa fa-user"></i> Add User</a></li>
								</ul>
							</div>
						</li>
						<li class="dropdown">
							<div class="btn-group">
								<a href="<?= $this->url('admin-series'); ?>" class="btn btn-inverse admin-btn dropdown-toggle"><i class="fa fa-film"></i> Series&nbsp;<i class="fa fa-caret-square-o-down"></i></a>
								<ul class="dropdown-menu">
									<li><a href="<?= $this->url('admin-series'); ?>"><i class="fa fa-film"></i> Add Series</a></li>
								</ul>
							</div>
						</li>
						<li class="dropdown">
							<div class="btn-group">
								<a href="<?= $this->url('admin-video'); ?>" class="btn btn-primary admin-btn dropdown-toggle"><i class="fa fa-film"></i> Videos&nbsp;<i class="fa fa-caret-square-o-down"></i></a>
								<ul class="dropdown-menu">
									<li><a href="<?= $this->url('admin-add-video'); ?>"><i class="fa fa-film"></i> Add Video</a></li>
								</ul>
							</div>
						</li>
						<li class="dropdown">
							<div class="btn-group">
								<a href="<?= $this->url('admin-admins'); ?>" class="btn btn-danger admin-btn dropdown-toggle"><i class="fa fa-group"></i> Admins&nbsp;<i class="fa fa-caret-square-o-down"></i></a>
								<ul class="dropdown-menu">
									<li><a href="<?= $this->url('admin-admin-add'); ?>"><i class="fa fa-user"></i> Add Admin</a></li>
								</ul>
							</div>
						</li>
					</ul>
				</div>
			</nav>
		</div>
        <div class="container" id="admin-<?= $this->controllerName(); ?>-<?= $this->actionName(); ?>">
            <?php echo $this->content; ?>
        </div> 
    </body>
</html>
	

	