<script type="text/template" id="search-template">
<% if (type == "ad") { %>
	<div class="col-sm-4 col-xs-6 google-ad loading" data-position="rectangle" ></div>
<% } else if (type == "category") { %>
	<div class="col-sm-4 col-xs-6 col-wide loading">
		<div class="video-preview category-preview">
			<a href="<%- link %>">
				<img alt="<%- escaped_title %>" src="<%- image %>" class="img-responsive preview-img img-<%- image_source %>">
			</a>
			<div class="carousel-caption category">
				<div class="video-title">
					<h3 title="<%- escaped_title %>" class="dot-text">
						<a href="<%- link %>">
							<div class="dot-text"><%= escaped_title %></div>
						</a>
					</h3>
				</div>
			</div>
		</div>
	</div>
<% } else if (type == "city") { %>
	<div class="col-sm-4 col-xs-6 col-wide loading">
		<div class="video-preview">
			<a href="<%- link %>">
				<img alt="<%- escaped_title %>" src="<%- image %>" class="img-responsive preview-img img-<%- image_source %>">
			</a>
			<div class="carousel-caption small">
				<div class="video-title">
					<h3 title="<%- escaped_title %>" class="dot-text">
						<a href="<%- link %>">
							<div class="dot-text">City: <%= escaped_title %></div>
						</a>
					</h3>
				</div>
			</div>
		</div>
	</div>
<% } else if (type == "user") { %>
	<div class="col-sm-4 col-xs-6 col-wide loading">
		<div class="video-preview">
			<a href="<%- link %>">
				<img alt="<%- escaped_title %>" src="<%- image %>" class="img-responsive preview-img img-<%- image_source %>">
			</a>
			<div class="carousel-caption small">
				<div class="video-title">
					<h3 title="<%- escaped_title %>" class="dot-text">
						<a href="<%- link %>">
							<div class="dot-text">User: <%= escaped_title %></div>
						</a>
					</h3>
					<h3 class="dot-text"></h3>
					<h3 title="<%- escaped_location %>" class="dot-text"><%- escaped_location %></h3>
				</div>
			</div>
		</div>
	</div>
<% } else if (type == "series") { %>
	<div class="col-sm-4 col-xs-6 col-wide loading">
		<div class="video-preview">
			<a href="<%- link %>">
				<img alt="<%- escaped_title %>" src="<%- image %>" class="img-responsive preview-img img-<%- image_source %>">
			</a>
			<div class="carousel-caption small">
				<div class="video-title">
					<h3 title="<%- escaped_title %>" class="dot-text">
						<a href="<%- link %>">
							<div class="dot-text">Series: <%= escaped_title %></div>
						</a>
					</h3>
					<h3 class="dot-text">
                        <a href="<%- user_profile %>">
							<div class="dot-text">by <%- user %></div>
						</a>
					</h3>
					<h3 title="<%- escaped_location %>" class="dot-text"><%- escaped_location %></h3>
					
				</div>
			</div>
		</div>
	</div>
<% } else {%>		
	<div class="col-sm-4 col-xs-6 col-wide loading">
		<div class="video-preview <%- position %>">
			<a href="<%- link %>">
				<img class="img-responsive preview-img img-<%- image_source %>" alt="<%- escaped_title %>" src="<%- image %>">
			</a>
			<div class="carousel-caption small">
				<div class="video-title">
					<h3 title="<%- escaped_title %>" class="dot-text">
						<a href="<%- link %>">
							<div class="dot-text"><%= escaped_title %></div>
						</a>
					</h3>
<% if (series_name == '') { %>	
					<h3 class="dot-text">
                        <a href="<%- user_profile %>">
							<div class="dot-text">by <%- user %></div>
						</a>
					</h3>
<% } else { %>		
					<h3 class="dot-text">
                        <a href="<%- link %>">
							<div class="dot-text">Series: <%- series_name %></div>
						</a>
					</h3>
<% } %>		
					<h3 title="<%- escaped_location %>" class="dot-text"><%- escaped_location %></h3>
				</div>
				<div class="info-button <%- position %>"
					title="" 
					data-original-title="<a href='<%- link %>'><%= escaped_title %></a> by <a href='<%- user_profile %>'><%= user %></a>"
					data-content="<%- escaped_location %><br/><%= escaped_logline %>
					<footer>
					<span class='video-duration'><i class='fa fa-clock-o'></i> <%= duration %></span>
					<span class='video-plays'><i class='fa fa-play'></i> <%= views %></span> 
					<span class='video-thumbs-up'><i class='fa fa-thumbs-up'></i> <%= rate_up %></span> 
					<span class='video-thumbs-down'><i class='fa fa-thumbs-down'></i> <%= rate_down %></span>
					<span class='video-comments'><i class='fa fa-comments'></i> <%= comment_count %></span>
					</footer>"
					data-toggle="popover">
					<i class="fa fa-info-circle"></i>
				</div>
			</div>
		</div>
	</div>
<% } %>			
</script>