<script type="text/template" id="video-template">
	<div class="video-preview" data-id="<%- id %>">
		<a href="<%- mediaLink %>" class="thumb_wrapper bg" style="background-image:
				url(<%- previewImage %>)">&nbsp;
			<!-- <img class="img-responsive preview-img img-vimeo" alt="<%- title %>" src="<%- previewImage %>"> -->
		</a>
		<div class="carousel-caption small">
			<div class="video-title">
				<h3 title="<%- title %>" class="dot-text">
					<a href="<%- mediaLink %>">
						<div class="dot-text"><%- title %></div>
					</a>
				</h3>

				<h3 class="dot-text">
					<a href="<%- profileLink %>">
						<div class="dot-text">by <%- username %></div>
					</a>
				</h3>

				<h3 title="<%- location %>" class="dot-text"><%- location %></h3>
			</div>
			<div class="info-button first" title="" data-original-title="<a href='<%- mediaLink %>'><%- title %></a> by <a href='<%- profileLink %>'><%- username %></a>" data-content="<%- location %><br/><%- logline %>
					<footer>
					<span class='video-duration'><i class='fa fa-clock-o'></i> <%- duration %></span>
					<span class='video-plays'><i class='fa fa-play'></i> <%- views %></span>
					<span class='video-thumbs-up'><i class='fa fa-thumbs-up'></i> <%- rate_up %></span>
					<span class='video-thumbs-down'><i class='fa fa-thumbs-down'></i> <%-rate_down %></span>
					<span class='video-comments'><i class='fa fa-comments'></i> <%- comment_count %></span>
					</footer>" data-toggle="popover">
				<i class="fa fa-info-circle" data-track="click" data-type="info" data-value="<%- id %>"></i>
			</div>
		</div>
	</div>

</script>

