<script type="text/template" id="video-template">
	<li>
		<div class="video-preview">
			<a href="<%- link %>">
				<img alt="<%- title %>" src="<%- image %>" class="img-responsive preview-img">
			</a>
		</div>
		<div class="video-info">
			<a href="<%- link %>">
				<h4><%- title %></h4>
			</a>
			Creator: <a class="user-link" href="<%- userlink %>"><%- username %></a>
			<div class="video-location"><%- location %></div>
		</div>
	</li>
</script>
