<div id="advertising-wrapper"></div>
<div class="container advertising-page">
	<div class="row">
		<div class="col-xs-12">
			<div class="container">
				<div class="row">
					<div class="col-xs-10">
						<h1>Advertise on TownSpot</h1>
						<h2 class="sub-header">Reach your local community online!</h2>
					</div>
					<div class="col-xs-2">
						<a href="/add-advertisement" class="btn btn-primary btn-large pull-right">Submit an Ad</a>
					</div>
				</div>
				<ul class="nav nav-pills white-oval">
					<li><a href="/assetmanager/files/About_TownSpot_Advertising.pdf">Why TownSpot?</a></li>
					<li><a href="#how-it-works" class="advertising-quick-links">How it Works</a></li>
					<li><a href="#our-audience" class="advertising-quick-links">Our Audience</a></li>
					<li><a href="#help-creating-ads" class="advertising-quick-links">Help Creating Ads</a></li>
					<li><a href="/files/Sales_Kit_FINAL-2012-12-03.zip" class="advertising-quick-links">Sales Kit</a></li>
				</ul>				
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-xs-12">
			<h2>Why Town<span class="highlight">Spot</span>?</h2>
			<img class="pull-left" src="/img/TSLogo.png">
			<h3>We're here to help your business reach new customers in your community</h3>
			<p>At TownSpot, we showcase videos of talented individuals to viewers from their city while connecting those viewers with the businesses that serve their community.</p>
			<p>By advertising with us, your business can reach high potential custom- ers that are seeking out information specifically about the area you serve. Communicate with people in your city who want to explore all that it has to offer.</p>
			<p>Each video featured on TownSpot is selected by our staff and certified as quality. This means that your ad will only appear before or beside content that is respectable
		and healthy for your brand. Additionally, you can choose which categories or individual video your ad will run near, to further your targeting to the specific audience you want.</p>
			<p>We'll help drive traffic to your website, raise your brand awareness, and bring new people through the front door of your location. Let us help you increase sales by sharing your message with your town.</p>
		</div>
	</div>
	<div class="row">
		<div class="col-xs-12 center">
			<h2>Downloads</h2>
			<a target="_blank" href="/assetmanager/files/TownSpot_Solutions.pdf" class="highlight">Small Business Solutions</a> | <a target="_blank" href="/assetmanager/files/About_TownSpot_Advertising.pdf" class="highlight">Why TownSpot Advertising?</a>
		</div>
	</div>
	<div class="row">
		<div class="col-xs-12">
			<a name="how-it-works"></a>
			<h2>How It Works</h2>
			<h3>We offer many ways for your business to spread your message on TownSpot, including:</h3>
			<div id="placeholder-block" class="container">
				<div class="row">
					<div class="col-xs-3">
						<img src="/img/VideoPlaceholder.jpg">
					</div>
					<div class="col-xs-9">
						<h3 class="highlight">Pre-roll Ads</h3>
						<p>This short video ad plays before videos based on your desired targeting.</p>
					</div>
				</div>
				<div class="row">
					<div class="col-xs-3">
						<img src="/img/VideoPlaceholder.jpg">
					</div>
					<div class="col-xs-9">
						<h3 class="highlight">Static pre-roll bumper</h3>
						<p>TownSpot can help you create a static pre-roll ad consisting of your company logo, a one to two sentence slogan, and the URL &amp; Address of your business with the option of voice-over narration.</p>
					</div>
				</div>
				<div class="row">
					<div class="col-xs-3">
						<img src="/img/VideoPlaceholder.jpg">
					</div>
					<div class="col-xs-9">
						<h3 class="highlight">TownSpot Shout Out</h3>
						<p>Let us speak on your behalf. TownSpot is happy to help you create what we like to call a "ShoutOut": a short video of a TownSpot representative introducing your business.</p>
					</div>
				</div>
				<div class="row">
					<div class="col-xs-12">
						<h3 class="highlight">IAB Display Units</h3>
						<p>Reach our users as they engage with the site, with prime placement of your display ad.</p>
					</div>
				</div>
				<div class="row">
					<div class="col-xs-5">
						<img src="/img/Leaderboard.jpg">
					</div>
					<div class="col-xs-7">
						<h3>Leaderboard Display</h3>
						<p>The leader board is the primary display ad for Townspot and is one of the first things our audience sees when visiting the site. It is prime placement on our homepage, City Spotlight, and all of our Discover pages.</p>
					</div>
				</div>
				<div class="row">
					<div class="col-xs-5">
						<img src="/img/Indvidual_Video_Comments.jpg">
					</div>
					<div class="col-xs-7">
						<h3>Sky Scraper &amp; Box Ads</h3>
						<p>Skyscraper and Box ads are located near the comment sections of our individual video pages.</p>
					</div>
				</div>
				<div class="row">
					<div class="col-xs-5">
						<img src="/img/CategoryBoxAd.jpg">
					</div>
					<div class="col-xs-7">
						<h3>Category Box Ad</h3>
						<p>This ad is located just below our category and genre selection and is in prime placement for viewers who are deciding what they want to explore.</p>
					</div>
				</div>
				<div class="row">
					<div class="col-xs-5">
						<img src="/img/FooterAd.jpg">
					</div>
					<div class="col-xs-7">
						<h3>Footer Display (729px x 90px)</h3>
						<p>The Footer is located at the bottom of the page. With a lower rate, this ad works great when partnered with other ad or for capturing the attention of browsing viewers, moving from page to page as they navigate the site.</p>
					</div>
				</div>
			</div>
			<p>All ad campaigns can be accommodated to fit large and small advertising budgets. For a detailed specs sheet including our rate card, send contact information and any questions to <a href="mailto:advertising@townspot.tv">advertising@townspot.tv</a>. Our trained advertising team will work with you to ensure your campaign reaches your target audience effectively.</p>
			<p>Once your ads are live, they will be monitored by your account representative to make sure they are at peak performance. After your campaign is complete, we'll send you a detailed analytics report of how they did!</p>
			<p>We know not everyone's an online marketer. So if any of this sounds unfamiliar, don't worry. Contact us and let's figure out how you can best connect with our audience and grow your business.</p>
		</div>
	</div>
	<div class="row">
		<div class="col-xs-12">
			<a name="our-audience"></a>
			<h2>Our Audience</h2>
			<p>We know that you have limited advertising resources and that it's important to allocate them effectively. With TownSpot, your ad spend is only for ads that are placed directly in front of viewers that show interest in the market you serve, exploring what their city has to offer.</p>
			<p>Our user base has a wide range of interests including music, arts, food, sports, local culture, and their city's community. As an advertiser, you are able to target your ads by video category, genre, and sub-genre allowing you to speak directly to those viewers with a specific interest of your choice.</p>
			<p>For example, if you think your business would benefit most from placement on videos in the 'Music' category, you can specify this on TownSpot! Furthermore, if you want to advertise not just on any music videos, but, more specifically, on videos in the 'Jazz' music genre, you can do that too!</p>
			<p>Don't waste your resources on ads served mostly to people living halfway across the world, with no potential of becoming daily customers of your business. Say hello and engage with the local crowd you've been trying to reach in your community.</p>
		</div>
	</div>
	<div class="row">
		<div class="col-xs-12">
			<a name="help-creating-ads"></a>
			<h2>Help Creating Ads</h2>
			<p>Whether you're new to advertising online or have been doing it for years, we will help make it easy, affordable, and effective to advertise on TownSpot.</p>
			<p>We'll start with what you have and help to build a powerful message.</p>
			<p>One of the most powerful options on TownSpot is video advertising, but we know that it can be difficult for a small business to dive into this medium. If you're interested in creating video advertisements for the first time, let us know. We can help you create a Pre-Roll Bumper Ad or Video Shout-Out. For more information take a look at our Ad Creation Document or submit what you have <a href="/add-advertisement">here</a>.</p>
		</div>
	</div>
</div>
			