<div class="container what-is-townspot">
	<div class="row">
		<div class="col-xs-12">
			<h2>What Makes Town<span class="highlight">Spot</span> Different?</h2>
			<p>With all of the content out there on the web, what makes TownSpot different? Well, as a video network and as a business, we strive for quality and connecting with our audience on a real level. No gimmicks, no ploys, just quality content reflective of your town and your community.</p>
			<p>TownSpot is about...</p>
		</div>
    </div>		
	<div class="row">
		<div class="col-xs-12">
			<img src="/img/what-is-townspot/icons_quality.png" class="about-img-right" align="top">
			<h3 class="highlight">Quality</h3>
			<p>All videos are verified by our staff as high quality and follow the <a href=http://www.townspot.tv/video-submission-agreement>TownSpot Content Policy</a></p>
			<p>Most people watch online videos due to some kind of referral. You are more inclined to view something shared by a friend because you trust their judgment. Well, TownSpot is like that friend whom you can rely on to bring you great videos that are actually relevant to you and your city. Trust us.</p>
		</div>
	</div>
	<div class="row">
		<div class="col-xs-12">
			<img src="/img/what-is-townspot/icons_local.png" class="about-img-left" align="top">
			<h3 class="highlight">Local</h3>
			<p>Videos originate from your city. The talent is local.</p>
			<p>There is a large sense of disassociation out on the web today. We watch content without really connecting. Town<span class="highlight">Spot</span> aims to give you a more dynamic viewing experience by showing you content from your city that is actually within your grasp. Explore and connect with your city's talent. What you see on Town<span class="highlight">Spot</span> today, could open a new adventure tomorrow.</p>
		</div>
	</div>
	<div class="row">
		<div class="col-xs-12">
			<img src="/img/what-is-townspot/icons_relevant.png" class="about-img-right" align="top">
			<h3 class="highlight">Relevant Advertisements</h3>
			<p>We show ads relative to your interest and your community.</p>
			<p>Advertisements shown on Town<span class="highlight">Spot</span> pertain to your city. We target our ads based on your interest so that you see real businesses offering products and services you actually want. Find a local restaurant, cool new store, or a fun activity. At Town<span class="highlight">Spot</span>, our ads contribute to the experience instead of taking away from it.</p>
			<p>Want to have your <a href="http://backstage.townspot.tv/advertise-2/">local business</a> on Town<span class="highlight">Spot</span>? Learn more about our advertising programs <a href="http://backstage.townspot.tv/advertise-2/">here.</a></p>
		</div>
	</div>
	<div class="row">
		<div class="col-xs-12">
			<img src="/img/what-is-townspot/icons_intuitive.png" class="about-img-left" align="top">
			<h3 class="highlight">Intuitive Navigation</h3>
			<p>Categories and genres help make searching for a video that interests you intuitive and easy.</p> 
			<p>Browsing through endless videos that have nothing to do with your interest can be a pain. With our <a href="http://www.townspot.tv/los-angeles/videos">Discover</a> browsing setup, you can find videos based on not just categories, but genres, sub-genres, buzz, release date, and more. And since all the videos are examined and organized by Town<span class="highlight">Spot</span> staff, you'll always be able to find videos for your interests.</p> 
		</div>
	</div>
	<div class="row">
		<div class="col-xs-12">
			<img src="/img/what-is-townspot/icons_intuitive.png" class="about-img-right" align="top">
			<h3 class="highlight">Experience</h3>
			<p>We focus on giving you the best viewing experience possible.</p> 
			<p>At Town<span class="highlight">Spot</span>, we value the viewing experience. We keep our ads short and work to make sure they don't hinder your enjoyment. We also avoid those annoying in-video pop up ads and annotations so you can enjoy your content distraction free. You can also use the Spotlight to have quality videos delivered to you on a steady stream so that you can relax and enjoy yourself without clicking from video to video.</p> 
		</div>
	</div>
	<div class="row">
		<div class="col-xs-12">
			<h3 class="highlight">Connection</h3>
			<p>Town<span class="highlight">Spot</span> aims to connect local audiences with local talent within their communities. To do this we have provided a number of tools to help fans keep up-to-date with the latest projects, events, and happenings of their favorite local artists. From on-page social integration to direct event and message posting, Town<span class="highlight">Spot</span> provides the tools to make sure content creators are not just getting a view, but a fan.</p> 
			<p>See how our process works in the video below.</p> 
		</div>
	</div>
	<div class="row">
		<div class="col-xs-12" align="center">
			<div class="media">
				<?= $this->VideoPlayer(
					1952,
					array(
						'width' => '90%',
						'preview_width' => 800,
						'preview_height' => 450,
						'include_sharing' => true
					)
				); ?>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-xs-12">
			<h4>Want To learn more? Visit the Backstage!</h4>
			<p><a href="http://backstage.townspot.tv">The Backstage</a> is your place learn about the inner-workings of Town<span class="highlight">Spot</span>.tv as well as our history, contact information, and our plans for the future. On top of information about Town<span class="highlight">Spot</span>, the Backstage offers up coverage on industry news, studies, press, content creator spotlights, guides, how-to's and media related to the growth of the online video industry.</p>
		</div>
    </div>		
</div>
<div class="modal fade" id="SetupError" tabindex="-1" role="dialog" aria-labelledby="SetupLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">x</button>
				<h4 class="modal-title" id="SetUpLabel">An Error has occurred</h4>
			</div>
			<div class="modal-body" id="SetupErrorMessage">
				Your browser currently does not have the Flash media plug-in needed to view the video. <br/>
				Please download the plugin from <a href="http://get.adobe.com/flashplayer/" target="_blank">Adobe - Install Adobe Flash Player</a>
			</div>
		</div>
	</div>
</div>
