<div class="container">
	<div class="row">
		<div class="col-xs-12">
			<h1>Content Policy</h1>
		</div>
	</div>
	<div class="row">
		<div class="col-xs-12">
			<p>TownSpot defines a quality video as one containing engaging or interesting elements that a public audience may find entertaining.  These elements are derived from the content of the video, not from its technical aspects or production value.</p>
			<p>No video that is in violation of local, state, or federal law will be permitted on TownSpot nor will any video containing explicit pornography.  TownSpot will not display any video that contains hateful, defamatory, or discriminatory speech that attacks, demeans, or is meant to incite hatred against any individual or group.  </p>
			<p>If you're not sure if your video meets the above qualifications, check out our Video Submission Tips located <a href="video-submission-tips">here.</a></p>
			<p>If you have any questions about our content policy, contact our legal department at <a href="mailto:legal@townspot.tv">legal@townspot.tv</a></p>
		</div>
	</div>		
</div>	