<div class="container">
	<div class="row-fluid">
		<div class="col-xs-12">
			<h1 class="page-header">TownSpot Community Standards</h1>
		</div>
	</div>
	<div class="row-fluid">
		<div class="col-xs-12">
			<h2>Your Conduct</h2>
			<ol class="spaced-list community-standards">
				<li>TownSpot is not for pornography or sexually explicit content. If this describes your video, even if it's a video of yourself, don't bother Submitting it to us. Also, be advised that we work closely with law enforcement and we report child exploitation.</li>
				<li>Don't post videos showing illegal or inappropriate activity that bears no relation to talent and skills that we aim to spotlight on TownSpot. Another common sense standard. This includes, but is not limited to, animal abuse, drug abuse, under-age drinking and smoking, or any illegal or questionably illegal activity.</li>
				<li>Graphic or gratuitous violence is not allowed. If your video shows someone being physically hurt, attacked, or humiliated, don't post it.</li>
				<li>Respect copyright. Only upload videos that you made or that you are authorized to use. This means don't upload videos you didn't make, or use Content in your videos that someone else owns the copyright to. This particularly important in videos using imagery or audio sampled or taken from someone else's work.</li>
				<li>We encourage free speech and defend everyone's right to express unpopular points of view. But we don't permit hate speech (speech which attacks or demeans a group based on race or ethnic origin, religion, disability, gender, age, veteran status, and sexual orientation/gender identity). In fact, we work closely with law enforcement and other organizations to help curtail it and identify perpetrators. </li>
				<li>Things like predatory behavior, stalking, threats, harassment, intimidation, invading privacy, revealing other people's personal information, and inciting others to commit violent acts or to violate the Terms and Conditions are taken very seriously. Anyone caught doing these things may be permanently banned from the Service and reported to the appropriate authorities</li>
				<li>Use your Member Account with good judgment for the main purpose of highlighting your characteristics, skills and talents associated with your Content. Don't misuse it by creating misleading descriptions, tags, titles or thumbnails in order to increase views. Posting large amounts of untargeted, unwanted or repetitive content, including comments and private messages is not acceptable. Not to mention it takes away from letting your talent shine on its own on TownSpot's website.</li>
			</ol>
			<br/>
			<h2>Our Conduct</h2>
			<p>It is important for you to appreciate that TownSpot is not just a platform to showcase talent. It is a community of artist and viewers who appreciate artists. As with every flourishing community, it takes work to keep it that way. We are constantly working with users towards that end and ask that you help us.</p>
			<p>Accordingly, when TownSpot receives notification about misuse of Member Accounts, inappropriate Content, or inappropriate conduct or comments by users, we take these seriously. <span class="bold">Be aware that what TownSpot, in its sole discretion, deems are serious or repeated violations may lead to account termination. It does not matter if it's a first-time or repeated offense: We reserve this right and will exercise it if we deem it necessary</span>.</p>
			<p>Of course, if your Member Account is terminated, the consequences are serious: You will not be allowed to create a new Member Account, which means you will no longer be able to participate in our community as an artist, user or in any other manner associated with the benefits of a Member Account. </p>
			<p>Please take this to heart and take it seriously. Enjoy the amazing access to talent, growing audiences and new horizons that TownSpot offers you. Just use your common sense and observe our policies in doing so. Thanks! </p>
		</div>
	</div>
</div>
