<div class="container">
	<div class="row">
		<div class="col-xs-12">
			<h1>TownSpot Video Submission Tips</h1>
		</div>
	</div>
	<div class="row">
		<div class="col-xs-12">
			<p class="video-submission-tips-sub-header">The purpose of this document is to provide users some helpful tips on understanding if their video will be approved for TownSpot or not. Each question is followed by a description and example.</p>
			<ol class="spaced-list video-submission-tips">
				<li>Is your video of quality? (Refer to <a href="content-policy">TownSpot Content Policy</a>)
					<ol class="spaced-list">
						<li>A video of a young child playing virtuosic piano music would qualify as something of quality.</li>
					</ol>
				</li>
				<li>Is your video entertaining?
					<ol class="spaced-list">
						<li>A video of a small child worried about his Halloween candy being eaten- only to find out his parents were playing a trick on him- would be an example of a submission that would be considered entertaining.</li>
					</ol>
				</li>
				<li>Do you own or have the rights to the Video in question?
					<ol class="spaced-list">
						<li>Did you shoot the video?  Or has the video's owner given you ownership?</li>
					</ol>
				</li>
				<li>Does your video abide by all local, state, and federal law?
					<ol class="spaced-list">
						<li>A video containing someone doing illegal drugs would not be accepted on TownSpot due to it's violation of local, state and federal laws.</li>
					</ol>
				</li>
				<li>Is the image quality so poor that its content is unperceivable?
					<ol class="spaced-list">
						<li>If your video is pixilated or distorted beyond the content's recognition, for example shot with a cell phone camera with poor resolution, it may not be appropriate for TownSpot.</li>
					</ol>
				</li>
				<li>Does your video directly attempt to promote or sell a product or service? (if so, please refer to our <a target="_blank" href="http://backstage.townspot.tv/advertise-2/">Advertising</a> page)
					<ol class="spaced-list">
						<li>Do you leave a phone number or a website? Or is your video a pure commercial for some product or business? If so, please refer to our Advertising page.</li>
					</ol>
				</li>
				<li>Does this video have a public audience?
					<ol class="spaced-list">
						<li>A video of you tying your shoes may be hold an audience of you and your proud parents, but does not illicit a public audience.</li>
					</ol>
				</li>
			</ol>
			<p>If you have any questions about if your video is appropriate for TownSpot, please do not hesitate to contact our Content Production team at <a href="mailto:content@townspot.tv">Content@townspot.tv</a></p>
		</div>
	</div>
</div>