<?php
function renderCat($cat,$level = 0,$current = null,$parents = '') {
    $pattern = "<option data-parents='%s' value='%s'%s>%s%s</option>\n";
    $pad = '';
    for($i = 0; $i < $level; $i++) {
        $pad .= '- ';
    }
    if(!empty($cat['parent_id'])) {
        if(!empty($parents)) $parents .= ',';
        $parents .= $cat['parent_id'];
    }
    $selected = ($cat['id'] == $current)? ' selected="selected"':'';
    $html = '';
    $html .= sprintf($pattern,$parents,$cat['id'],$selected,$pad,$cat['label']);
    if(!empty($cat['children'])) {
        $level++;
        foreach($cat['children'] as $child) {
            $html .= renderCat($child,$level,$current,$parents);
        }
    }
    return $html;
}
?>
<div class="row" id="channelsurf">
    <div class="col-md-2 sidebar">
        <div class="stateSelector">
            <label>State:</label>
            <select class="form-control">
                <option value="0">All States</option>
            <?php foreach($states as $s): ?>
                <option value="<?= $s['id'] ?>" <?= ($s['id'] == $state)? 'selected="1"':'' ?>><?=$s['name']?> (<?= $s['media_count'] ?>)</option>
            <?php endforeach; ?>
            </select>
        </div>
        <?php
            $cityClass = ' hidden';
            if($state) {
                $cityClass = '';
            }
        ?>
        <div class="citySelector<?= $cityClass ?>">
            <label>City:</label>
            <select class="form-control">
                <option value="0">All Cities</option>
                <?php if($state): ?>
                <?php foreach($cities[$state] as $c): ?>
                    <option value="<?= $c['id'] ?>" <?= ($c['id'] == $city)? 'selected="1"':'' ?>><?=$c['name']?> (<?= $c['media_count'] ?>)</option>
                <?php endforeach; ?>
                <?php else: ?>
                    <option value="">Please Select a State</option>
                <?php endif; ?>
            </select>
        </div>
        <div class="categorySelector">
            <label>Category:</label>
            <select class="form-control">
                <option value="0">All Categories</option>
            <?php foreach($categories as $c): ?>
                <?php if(is_object($category)) {
                    $category = $category->getId();
                } else {
                    $category = 0;
                }
                ?>
                <?= renderCat($c,0,$category); ?>
            <?php endforeach; ?>
            </select>
        </div>
        <div class="sortSelector">
            <label>Sort:</label>
            <select class="form-control">
                <option value="RAND()">Random</option>
                <option value="media.views DESC">Popularity</option>
            </select>
        </div>
        <br/>
        <button id="applyFilters" class="btn-primary form-control">Apply Filters</button>
        <div class="currentlyWatching">
            <h3>Currently Watching:</h3>
            <a href="/channelsurf">All Videos</a>
        </div>
    </div>
    <div class="col-md-8 mainchannel">
        <div class="row" id="video">
            <div class="col-xs-12">
                <div class="media">
                    <?= $this->VideoPlayer(
                        1952,
                        array(
                            'width' => '100%',
                            'preview_width' => 800,
                            'preview_height' => 450,
                            //'include_sharing' => true,
                            'include_info' => true,
                            'include_buttons' => true,
                        )
                    ); ?>
                </div>
            </div>
        </div>
        <div class="row video-info">
            <div class="col-sm-12">
                <div class="row">
                    <div class="col-xs-12">
                        <h3>Description:</h3>
                        <div class="expandable description">
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-xxs-5 col-xs-4 col-sm-3">
                        <h3>Location:</h3>
                    </div>
                    <div class="col-xxs-7 col-xs-8 col-sm-9">
                        <ul class="boxed-list">
                            <li class="city"><a href="#"></a></li>
                            <li class="state"><a href="#"></a></li>
                        </ul>
                    </div>
                </div>
                <div class="row">
                    <div class="col-xxs-5 col-xs-4 col-sm-3">
                        <h3>Genres:</h3>
                    </div>
                    <div class="col-xxs-7 col-xs-8 col-sm-9">
                        <ul class="boxed-list genres">

                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="row comments-row">
            <div class="col-xs-12">
                <div class="col-xxs-5 col-xs-4 col-sm-3 comments-header">
                    <h3>Comments:</h3>
                </div>
            </div>
            <div class="row form-group">
                <div class="col-xs-9 nopadding-right full-320">
                    <input type="text" class="col-sm-8 form-control" placeholder="Leave a Comment" id="comment-field">
                </div>
                <div class="col-xs-3 nopadding-left full-320">
                    <button class="form-control btn interaction-button" id="comment-submit">Comment</button>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-12">
                    <div class="alert alert-block alert-error" id="comment-error">
                        <button type="button" class="close" data-dismiss="alert">X</button>
                        <h4 class="alert-heading"></h4>
                        <p class="alert-body"></p>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-12" id="comments">
                    <ul id="comment-list">
                    </ul>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-12">
                    <div id="comment-navigation-down" style="display: none;"><button class="btn btn-default next col-xs-12"><i class="fa fa-chevron-down"></i></button></div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-2">
        <div class="row">
            <h3>&nbsp;&nbsp;Up Next</h3>
        </div>
        <div class="controls up hidden">
            <button class="form-control"><i class="fa fa-chevron-up"></i></button>
        </div>
        <div class="row" id="videos">

        </div>
        <div class="controls down">
            <button class="form-control"><i class="fa fa-chevron-down"></i></button>
        </div>
    </div>
</div>

<script>

    var stateId = <?= $state?$state:0 ?>;
    var cityId = <?= $city?$city:0 ?>;
    var categoryId = <?= $category?$category:0 ?>;
    var notThese = 0;
    var sort = 0;
    var limit = 5;
    var mediaList = [];
    var mediaIndex = 0;
    var categories = <?= json_encode($categories) ?>;
    var flatCats = <?= json_encode($flatCats) ?>;
    var cities = <?= json_encode($cities) ?>

    $('.stateSelector select').change(function(){
        var $state = $(this);
        stateId = $state.val();
        if(stateId != 0) {
            $('.citySelector').removeClass('hidden');
        } else {
            $('.citySelector').addClass('hidden');
        }
        cityId = 0;
        var $city = $('.citySelector select');

        $city.children().remove();
        $city.append('<option value="0">All Cities</option>');
        $(cities[$state.val()]).each(function(){
            $city.append('<option value="'+ this.id +'">'+ this.name +' ('+ this.media_count +')</option>');
        });
        $('.categorySelector select').val(0);
        $('.categorySelector select').change();
    });

    $('.citySelector select').change(function(){
        var $city = $(this);
        cityId = $city.val();
        $('.categorySelector select').val(0);
        $('.categorySelector select').change();
    });

    $('.categorySelector select').change(function(){
        var $cat = $(this);
        categoryId = $cat.val();
    });

    $('.sortSelector select').change(function(){
        var $sort = $(this);
        sort = $sort.val();
    });

    $('#applyFilters').click(function(){
        getInit();
    });

    $('#videos').on('click','.nextVideo a.playMe',function(e){
        e.preventDefault();
        playThis($(this).parents('.nextVideo').attr('data-index'));
        //fetchNext();
    });

    function playThis(index) {
        var media = mediaList[index];
        playMedia(media);
    }

    function renderMedia(media, index) {
        if(typeof index == 'undefined') {
            index = 0;
        }
        var html = '';
        html += '<div class="col-xs-12 nextVideo" data-id="'+media.id+'" data-index="'+index+'">';
        html += '		<div class="video-preview">';
        html += '			<a href="'+ media.id +'" class="playMe">';
        html += '				<img class="img-responsive preview-img img-youtube" alt="'+ media.title +'" src="'+ media.image +'">';
        html += '			</a>';
        html += '			<div class="carousel-caption small">';
        html += '				<div class="video-title">';
        html += '					<h3 title="'+ media.title +'" class="dot-text">';
        html += '						<a href="'+ media.id +'" class="playMe">';
        html += '							<div class="dot-text">'+ media.title +'</div>';
        html += '						</a>';
        html += '					</h3>';
        html += '	';
        html += '					<h3 title="'+ media.location +'" class="dot-text">'+ media.location +'</h3>';
        html += '				</div>';
        html += '				<div class="info-button first" title="" data-original-title="<a href=\''+ media.link +'\'>'+ htmlEncode(media.escaped_title) +'</a> by <a href=\''+ media.user_profile +'\'>'+ media.user +'</a>" data-content="'+ media.location +'<br/>'+ htmlEncode(media.description);
        html += '					<footer>';
        html += '					<span class=\'video-duration\'><i class=\'fa fa-clock-o\'></i> '+ media.duration +'</span>';
        html += '					<span class=\'video-plays\'><i class=\'fa fa-play\'></i> '+ media.views +'</span> ';
        html += '					<span class=\'video-thumbs-up\'><i class=\'fa fa-thumbs-up\'></i> '+ media.rate_up +'</span> ';
        html += '					<span class=\'video-thumbs-down\'><i class=\'fa fa-thumbs-down\'></i> '+ media.rate_down +'</span>';
        html += '					<span class=\'video-comments\'><i class=\'fa fa-comments\'></i> '+ media.comment_count +'</span>';
        html += '					</footer>" data-toggle="popover">';
        html += '					<i class="fa fa-info-circle"></i>';
        html += '				</div>';
        html += '			</div>';
        html += '		</div>';
        html += '	</div>';

        return html;
    }

    function getSurfLink() {
        var state = $('.stateSelector option:selected').text().replace(/ \([0-9]*\)/,'');
        var newText = state + ', ';
        if(state == 'All States') state = 'all-states';
        var city = $('.citySelector option:selected').text().replace(/ \([0-9]*\)/,'');
        newText += city + '<br>';
        if(city == 'All Cities') city = 'all-cities';
        var cats = '';
        if(typeof $('.categorySelector option:selected').attr('data-parents') != 'undefined') {
            var parents = $('.categorySelector option:selected').attr('data-parents');
            parents = parents.split(',');
            console.log(parents);
            for(x in parents) {
                if(parents[x] != '') {
                    newText += flatCats[parents[x]] + '/';
                    cats += flatCats[parents[x]].replace(/\//, '+') + '/'
                }
            }

            cats += $('.categorySelector option:selected').text().replace(/^[ -]*/,'');
            newText += $('.categorySelector option:selected').text().replace(/^[ -]*/,'');;
        }
        var url = state + '/' + city + '/' + cats;
        url = '/channelsurf/' + url.toLowerCase().replace(/ /g,'_');
        $('.currentlyWatching a').attr('href',url);
        $('.currentlyWatching a').html(newText);
        console.log(url);
    }

    function htmlEncode(value){
        //create a in-memory div, set it's inner text(which jQuery automatically encodes)
        //then grab the encoded contents back out.  The div never exists on the page.
        return $('<div/>').text(value).html();
    }

    function htmlDecode(value){
        return $('<div/>').html(value).text();
    }

    function playMedia(media) {
        //$('#videos div[data-id='+media.id+']').remove();
        //console.log($('#videos div[data-id='+media.id+']'));
        $('.nextVideo').removeClass('nowPLaying');
        $('.nextVideo[data-id='+media.id+']').addClass('nowPLaying');
        var playlist = [{
            image: media.image,
            file: media.url,
            sharing: {
                code: encodeURI("<iframe src='/embed/"+ media.id +"/"+media.escaped_title+"' width='640' height='426' frameborder='0' allowfullscreen></iframe>"),
                link: media.link
            }

        }];
        jwplayer('media-player').load(playlist);


        $('.description').html(media.logline);
        $('.state a').text(media.state);
        $('.state a').attr('href','/discover/' + encodeURIComponent(media.state));
        $('.city a').text(media.city);
        $('.city a').attr('href','/discover/' + encodeURIComponent(media.city) + '/' + encodeURIComponent(media.state));
        $('.videoTitle').text(media.title);
        $('.videoAuthor a').attr('href',media.user_profile);
        $('.videoAuthor a').text(media.user);
        $('#up-ratings').text(media.rate_up);
        $('#down-ratings').text(media.rate_down);
        $('.videoViews').text("View Count: " + media.views);
        $('#videos div[data-id='+media.id+'] .video-preview').addClass('nowPlaying');

        for(x in media.categories) {
            $('.genres').append('<li><a href="'+ media.categories[x].url +'">'+ media.categories[x].name +'</a></li>');
        }

        $().Interactions({
            userid: <?= ($this->zfcUserIdentity()) ? $this->zfcUserIdentity()->getId() : 0; ?>,
            videoid: media.id,
            creator: media.user,
            favorite: false,
            following: false
        });

        jwplayer('media-player').play(true);
    }

    function getNext() {
        mediaIndex = $('.nextVideo:first').attr('data-index');
        media = mediaList[mediaIndex];
        playMedia(media);
    }

    $('.controls.up button').click(function(e){
        e.preventDefault();
        prevVids();
    });

    $('.controls.down button').click(function(e){
        e.preventDefault();
        nextVids();
    });

    function nextVids() {
        $('.nextVideo:visible:first').hide();
        $('.nextVideo[hidden]:first').removeAttr('hidden');
        fetchNext();
        $('.controls.up').removeClass('hidden');
    }

    function prevVids() {
        $('.nextVideo:visible:first').prev().show();
        $('.nextVideo:visible:last').hide();
        if($('.nextVideo:visible:first').attr('data-id') == mediaList[0].id) {
            $('.controls.up').addClass('hidden');
        }
    }

    function fetchNext(number) {
        if(typeof number == 'undefined') {
            number = 1;
        }
        $.post('/api/media/channelsurf',
            {
                state: stateId,
                city: cityId,
                category: categoryId,
                sort: sort,
                notThese: notThese,
                limit: number
            }, function(response){
                if(response.success) {
                    for(x in response.data.media) {
                        var newMedia = response.data.media[x];
                        mediaList.push(newMedia);
                        notThese.push(newMedia.id);
                        $('#videos').append(renderMedia(newMedia, mediaList.length - 1));
                        $('.nextVideo:visible:last').attr('hidden',1);
                    }
                    setInfoButtons();
                }
            }
        );
    }

    function getInit() {
        $.post('/api/media/channelsurf',
            {
                state: stateId,
                city: cityId,
                category: categoryId,
                sort: sort,
                notThese: notThese,
                limit: 8
            }, function(response){
                if(response.success) {
                    $('#videos').children().remove();
                    data = response.data.media;
                    mediaList = data;
                    if(notThese == 0) notThese = [];
                    for (x in data) {
                        media = data[x];
                        notThese.push(media.id);
                        $('#videos').append(renderMedia(media,x));
                        if(x == 0) {
                            playMedia(media,true);
                        }


                    }
                    $('.nextVideo:visible:nth-child(n+5)').attr('hidden',1);
                    setInfoButtons();
                    jwplayer('media-player').play(true);
                }
            }
        );
        getSurfLink();
    }

    getInit();



    jwplayer('media-player').onPlaylistComplete(function(){
        getNext();
    })
</script>