<script src="/js/discoverpage.js"></script>
<div class="row">
<?php if ($this->matchesFound) { ?>
	<div class="row" id="discover-sort">
		<div class="col-xs-12 sort-select">
			<select name="sort" id="sort">
<?php 
	$sorts = array(
		'title:asc'			=> 'Alphabetical [A-Z]',
		'title:desc'		=> 'Alphabetical [Z-A]',
		'created:desc'		=> 'Date Added [Most Recent First]',
		'created:asc'		=> 'Date Added [Most Recent Last]',
		'views:desc'		=> 'Play Count [Most First]',
		'views:asc'			=> 'Play Count [Least First]',
	);
	foreach ($sorts as $key => $value) {
		if ($key == $this->sortTerm) {
			print '<option value="' . $key . '" selected="selected">' . $value . '</option>';
		} else {
			print '<option value="' . $key . '">' . $value . '</option>';
		}
	}
?>
			</select>
		</div>
	</div>
<?php } ?>
<?php if (!$this->matchesFound) { ?>
	<div class="row">
		<div class="col-xs-12">
Sorry no results found<br/>
Try narrowing your search
		</div>
	</div>
<?php } ?>
	<div class="row" id="search-results"></div>
	<div class="row loading-spinner">
		<div class="col-xs-12">
			<img class="data-loading" src="/img/loading.gif">
		</div>
	</div>
</div>
<div aria-hidden="true" id="Loading" aria-labelledby="Loading" role="dialog" tabindex="-1" class="modal fade" style="display: none;">
    <div class="modal-dialog modal-sm">
      <div class="modal-content">
        <div class="modal-body">
			<img class="data-loading" src="/img/loading.gif">
			<div>Loading...</div>
        </div>
      </div>
    </div>
</div>
<br/>
<br/>
<br/>
<script> 
	$('.explore-btn-wrapper').addClass('hidden-explore-btn-wrapper').removeClass('explore-btn-wrapper').css('display','none');
</script>
<?= $this->partial('partials/backbone/search-template.phtml'); ?>
<script>
<?php if ($this->matchesFound) { ?>
var foo = $().Discover({
	searchId: '<?= $this->searchId; ?>',
	country: '<?= $this->country; ?>',
	province: '<?= $this->province; ?>',
	city: '<?= $this->city; ?>',
	categoryId: '<?= $this->categoryId; ?>',
	sortTerm: '<?= $this->sortTerm; ?>',
	terms: <?= $this->terms; ?>,
	page: <?= $this->page; ?>,
	data: <?= $this->data; ?>
});
<?php } else { ?>
$().Discover({
	province: '<?= $this->province; ?>',
	city: '<?= $this->city; ?>',
	categoryId: '<?= $this->categoryId; ?>',
	sortTerm: '<?= $this->sortTerm; ?>',
	terms: <?= $this->terms; ?>
});
<?php } ?>
</script>
