<div id="createPlaylist" class="modal fade" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Create New Talent Show</h4>
            </div>
            <div class="modal-body">
                <form>
                    <input type="hidden" id="playlistId" value="<?= $id? $id : '' ?>"/>
                    <div class="form-group">
                        <label for="name">Name</label>
                        <input type="text" class="form-control" id="playlistName">
                    </div>
                    <div class="form-group">
                        <label for="description">Description</label>
                        <textarea name="playlistDescription" id="playlistDescription" class="form-control"></textarea>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Create</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->