<div class="container" id="videoUpload">
    <div class="row col-md-10 col-md-offset-1">
        <form id="submitForm" action="/admin/video/edit/<?= $data['id'] ?>" method="POST">
        <div class="col-sm-12">
            <h2>Edit a Video</h2>
            <?= $headForm ?>
        </div>
        <div class="col-md-8">
            <?= $mainForm ?>
        </div>
        <div class="col-md-4">
            <?= $videoMediaForm ?>
        </div>
        <div class="row">
            <div class="row">
                <div class="col-md-10 col-md-offset-1 form-group">
					<button id="submit" class="form-control btn btn-primary" type="submit">Submit Video</button>
                </div>
            </div>
        </div>
		</form>
    </div>
    <script>
        upload.init();

        $('<button style="position: relative; z-index: 1;" class="form-control" id="genthumbs"><i class="fa fa-image"></i> Generate Thumbs</button>')
            .insertAfter('#previewImage').click(function(e){
            e.preventDefault();
                window.open('/admin/video/thumbs/' + <?= $data['id'] ?>);
        });
    </script>
