<h1>Video Management</h1>
<div class="row breadcrumb-wrapper">
	<div class="col-sm-8">
		<ol class="breadcrumb">
			<li><a href="#">Home</a></li>
			<li class="active">Videos</li>
		</ol>	
	</div>
	<div class="col-sm-4">
		<a class="btn btn-default admin-btn pull-right" href="<?= $this->url('admin-add-video'); ?>">Add Video</a>
	</div>
</div>
<br/>
<div class="row" id="admin-search">
	<div class="col-sm-12">
		<div class="container">
			<div class="row">
				<div class="col-sm-12"><b>Search Videos</b></div>
			</div>
			<div class="row">
				<div class="col-sm-2">
					<label>Title</label><br/>
					<input id="search-title" type="text" placeholder="Video Title" class="col-sm-12">
				</div>
				<div class="col-sm-2">
					<label>Artist Name</label><br/>
					<input id="search-username" type="text" placeholder="Artist Name" class="col-sm-12">
				</div>
				<div class="col-sm-2">
					<label>State</label>
					<select id="search-province" data-ref="State" data-target="search-city" class="col-sm-12">
						<option value="">All</option>
<?php foreach ($this->provinces as $province) { ?>
						<option value="<?= $province['id']; ?>"><?= $province['name']; ?></option>
<?php } ?>
					</select>
				</div>
				<div class="col-sm-2">
					<label>City</label>
					<select id="search-city" data-ref="City" class="col-sm-12" disabled="disabled">
						<option value="">All</option>
					</select>
				</div>
				<div class="col-sm-2">
					<label>Added On or After</label>
					<input id="search-created-after" type="text" class="col-sm-8 datefield"></i>
				</div>
				<div class="col-sm-2">
					<label>Added On or Before</label>
					<input id="search-created-before" type="text" class="col-sm-8 datefield"></i>
				</div>
			</div>
			<div class="row">
				<div class="col-sm-12 pull-right">
					<label>Status:</label><br />
					<select id="search-status">
						<option value="">All</option>
						<option value="1">Approved Videos</option>
						<option value="0">Unapproved Videos</option>
					</select>
				</div>
			</div>
		</div>
	</div>
</div>
<div class="row">
	<div class="col-sm-12" id="record-list-wrapper">
		<table id="record-list-results">
			<thead>
				<tr>
					<th class="check-field"></th>
					<th class="active id-field">Id <i id="admin-sort-id" class="icon-admin-sort icon-admin-sort-up"></i></th>
					<th class="title-field">Title <i id="admin-sort-title" class="icon-admin-sort icon-admin-sort-undefined"></i></th>
					<th class="series-field">Series/ Episode <i id="admin-sort-series" class="icon-admin-sort icon-admin-sort-undefined"></i></th>
					<th class="username-field">Username <i id="admin-sort-username" class="icon-admin-sort icon-admin-sort-undefined"></i></th>
					<th class="location-field">Location <i id="admin-sort-location" class="icon-admin-sort icon-admin-sort-undefined"></i></th>
					<th class="views-field">Views <i id="admin-sort-views" class="icon-admin-sort icon-admin-sort-undefined"></i></th>
					<th class="added-field">Added <i id="admin-sort-added" class="icon-admin-sort icon-admin-sort-undefined"></i></th>
					<th class="status-field">Approved <i id="admin-sort-status" class="icon-admin-sort icon-admin-sort-undefined"></i></th>
					<th class="actions-field">Actions</th>
				</tr>
			</thead>
			<tbody>
			</tbody>
		</table>
	</div>
</div>
<script src="/js/mediaSearch.js" type="text/javascript"></script>
<script>
<?php if ($this->type !== null) { ?>
$('#search-status').val(<?= $this->type; ?>);
<?php } ?>
$().mediaSearch({});
</script>
