<h1>Video Management</h1>
<div class="row breadcrumb-wrapper">
	<div class="col-sm-12">
		<ol class="breadcrumb">
			<li><a href="#">Home</a></li>
			<li href="/admin/video">Videos</li>
			<li class="active">View Video</li>
		</ol>	
	</div>
</div>
<input type="hidden" id="id" value="<?= $this->media->getId(); ?>">
<br/>
<div class="row">
	<div class="col-sm-12">
		<h1>View Video - <?= $this->media->getTitle(); ?> (<?= $this->media->getId(); ?>)</h1>
	</div>
</div>
<div class="row">
	<div class="col-sm-12">
		<div class="btn-group pull-right" role="group">
			<a href="/admin/video/edit/<?= $record['Video']['id']; ?>" class="btn btn-default"><i class="fa fa-pencil-square-o"></i> Edit Video</a>
			<a id="delete" href="#" class="btn btn-default" data-ref="<?= $this->media->getId(); ?>">x Delete Video</a>
<?php if ($this->media->getApproved()) { ?>
			<a id="unapprove" href="#" class="btn btn-default" data-ref="<?= $this->media->getId(); ?>"><i class="fa fa-film"></i> UnApprove Video</a>
<?php } else { ?>
			<a id="approve" href="#" class="btn btn-default" data-ref="<?= $this->media->getId(); ?>"><i class="fa fa-film"></i> Approve Video</a>
<?php } ?>
			<button type="button" class="btn btn-default"><i class="fa fa-envelope"></i> Send Message to Video Artist</button>
<?php if ($this->referrer) { ?>
			<a href="<?= $this->referrer; ?>" class="btn btn-default"> Return to Previous Page</a>
<?php } ?>			
		</div>
	</div>
</div>

<div class="row">
	<div class="col-sm-12">
		<div role="tabpanel">
			<ul id="videoTab" class="nav nav-tabs" role="tablist">
				<li role="presentation" class="active"><a href="#video-profile" id="video-tab-profile" role="tab" data-toggle="tab">Video Info</a></li>
				<li role="presentation"><a href="#video-comments" role="tab" id="video-tab-comments" data-toggle="tab">Comments</a></li>
				<li role="presentation"><a href="#video-fans" role="tab" id="video-tab-fans" data-toggle="tab">Fans</a></li>
			</ul>
			<div id="videoTabContent" class="tab-content">
				<div role="tabpanel" class="tab-pane fade in active" id="video-profile">
					<div class="row">
						<div class="col-sm-12">
							<div class="row">
								<div class="col-sm-3 header">Artist</div>
								<div class="col-sm-9"><?= $this->media->getUser()->getUsername(); ?></div>
							</div>
							<div class="row">
								<div class="col-sm-3 header">Location</div>
								<div class="col-sm-9"><?= $this->media->getLocation(true); ?></div>
							</div>
							<div class="row">
								<div class="col-sm-3 header">Title</div>
								<div class="col-sm-9"><?= $this->media->getTitle(); ?></div>
							</div>
							<div class="row">
								<div class="col-sm-3 header">Logline</div>
								<div class="col-sm-9"><?= $this->media->getLogline(); ?></div>
							</div>
							<div class="row">
								<div class="col-sm-3 header">Description</div>
								<div class="col-sm-9"><?= $this->media->getDescription(); ?></div>
							</div>
							<div class="row">
								<div class="col-sm-3 header">Allow Contact</div>
								<div class="col-sm-9">
									<?php if ($this->media->getAllowContact()) { ?>
										<i class="fa fa-check-square-o"></i>
									<?php } else { ?>
										<i class="fa fa-square-o"></i>
									<?php } ?>
								</div>
							</div>
							<div class="row">
								<div class="col-sm-3 header">Approved</div>
								<div class="col-sm-3">
									<?php if ($this->media->getApproved()) { ?>
										<i class="fa fa-check-square-o"></i>
									<?php } else { ?>
										<i class="fa fa-square-o"></i>
									<?php } ?>
								</div>
								<div class="col-sm-3 header">Approved By</div>
								<div class="col-sm-3">
									<?php if ($this->media->getAdmin()) { ?>
										<?= $this->media->getAdmin()->getUsername(); ?>
									<?php } ?>
								</div>
							</div>
							<div class="row">
								<div class="col-sm-3 header"></div>
								<div class="col-sm-9">
									<div id='media-player'></div>
<?php if ($video_url = $this->media->getMediaUrl()) {} 
	   else {	$video_url = $this->media->getUrl();	 }
?>	
									<script type="text/javascript">
										var sPrimary = 'html5';
										if (/Chrome/.test(navigator.userAgent) && /Google Inc/.test(navigator.vendor)) {
											sPrimary = 'flash';
										}
										jwplayer('media-player').setup({
											width: '100%',
											aspectratio : "3:2",
											stretching: 'uniform',
											image: "<?= $this->media->getPreviewImage(); ?>",
											file: "<?= $video_url; ?>",
											primary: sPrimary
										});
									</script>
								</div>
							</div>
							<div class="row">
								<div class="col-sm-3 heading"><label for="VideoCategories" class="control-label">Categories</label></div>
								<div class="col-sm-9">
									<div id="categories-tree"></div>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div role="tabpanel" class="tab-pane fade" id="video-comments">
					<table width="100%" cellspacing="0" cellpadding="0" border="0" id="video-comments-table" class="display dataTable" aria-describedby="user_events_datatable" style="width: 100%;">
						<thead>
							<tr role="row">
								<th class="sorting_asc" role="columnheader" tabindex="0" aria-controls="video-comments-table" rowspan="1" colspan="1" style="width: 5%;">ID</th>
								<th class="sorting" role="columnheader" tabindex="0" aria-controls="video-comments-table" rowspan="1" colspan="1" style="width: 15%;">Username</th>
								<th class="sorting" role="columnheader" tabindex="0" aria-controls="video-comments-table" rowspan="1" colspan="1" style="width: 15%;">Date</th>
								<th role="columnheader" tabindex="0" aria-controls="video-comments-table" rowspan="1" colspan="1" style="width: 50%;">Comment</th>
								<th class="" role="columnheader" tabindex="0" aria-controls="video-comments-table" rowspan="1" colspan="1" style="width: 15%;"></th>
							</tr>
						</thead>
						<tbody aria-live="polite" aria-relevant="all">
<?php foreach ($this->media->getComments() as $comment) { ?>
							<tr id="Comment-<?= $e['id']; ?>" class="<?= ($i % 2) ? 'odd' : 'even'; ?>"">
								<td class="sorting_1"><?= $e['id']; ?></td>
								<td class="sorting_1"><?= $e['User']['username']; ?></td>
								<td class="sorting_1"><?= date('m/d/Y H:i',strtotime($e['created'])); ?></td>
								<td class="sorting_1"><?= $e['comment']; ?></td>
								<td><i class="icon-remove delete-request" data-ref="<?= $e['id']; ?>" data-func="delete" data-type="Comment"></i></td>
							</tr>
<?php } ?>
						</tbody>
					</table>
				</div>
				<div role="tabpanel" class="tab-pane fade" id="video-fans">
					<table width="100%" cellspacing="0" cellpadding="0" border="0" id="video-fans-table" class="display dataTable" aria-describedby="user_events_datatable" style="width: 100%;">
						<thead>
							<tr role="row">
								<th class="sorting_asc" role="columnheader" tabindex="0" aria-controls="video-fans-table" rowspan="1" colspan="1" style="width: 5%;">ID</th>
								<th class="sorting" role="columnheader" tabindex="0" aria-controls="video-fans-table" rowspan="1" colspan="1" style="width: 80%;">Username</th>
								<th class="" role="columnheader" tabindex="0" aria-controls="video-fans-table" rowspan="1" colspan="1" style="width: 15%;"></th>
							</tr>
						</thead>
						<tbody aria-live="polite" aria-relevant="all">
<?php foreach ($record['UserFavorite'] as $i => $e) { ?>
							<tr id="Comment-<?= $e['id']; ?>" class="<?= ($i % 2) ? 'odd' : 'even'; ?>"">
								<td class="sorting_1"><?= $e['id']; ?></td>
								<td class="sorting_1"><?= $e['User']['username']; ?></td>
								<td><i class="icon-remove delete-request" data-ref="<?= $e['id']; ?>" data-func="delete" data-type="UserFavorite"></i></td>
							</tr>
<?php } ?>
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>