<div class="container" id="userProfile">
<div class="row">
    <div class="col-sm-4 hidden-xs" id="username">
        <?= $user->getDisplayName() ?>
    </div>
    <div class="col-sm-8">
        <ul class="nav nav-pills pull-right">
            <?php if ($canEdit): ?>
                <li><a href="/user/manageseries">Manage My Series</a></li>
            <?php endif; ?>
            <li class="active"><a href="#profile" data-toggle="tab">Profile</a></li>
            <!-- <li><a href="#events" data-toggle="tab">Events</a></li> -->
            <li><a href="#videos" data-toggle="tab">Videos</a></li>
            <?php if($canEdit): ?>
                <li><a href="#favorites" data-toggle="tab">Favorites</a></li>
            <?php endif; ?>
        </ul>
    </div>

</div>
<div class="tab-content">
<div class="tab-pane active" id="profile">
<div class="row">

    <div class="col-sm-6" id="userDetails">
        <div class="row edit">
            <div class="col-sm-12">
                <?php if($canEdit) : ?><a href="/user/edit"><i class="fa fa-edit pull-right"></i></a><?php endif; ?>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-6">
                <?php if(
                    preg_match("/fbcdn/",$user->getImageUrl())
                    || preg_match("/googleusercontent/",$user->getImageUrl())
                    || preg_match("/twimg/",$user->getImageUrl())
                ) : ?>
                <img class='profile-pic img-responsive' src="<?= $user->getImageUrl() ?>" alt="a"/>
                <?php else: ?>
                <img class='profile-pic img-responsive' src="<?= $this->img('user',$user->getId(),260) ?>" alt="a"/>
                <?php endif; ?>
                <h3>Username</h3>
                <div><?= $user->getUsername() ?></div>
                <?php if ($canEdit && $authdUser) : ?>
                    <h3>Email</h3>
                    <div><?= $user->getEmail() ?></div>
                <?php elseif($user->getAllowContact()): ?>
                    <div class="row">
                        &nbsp;
                    </div>
                    <div class="row">
                        <?php if(!$canEdit && $authdUser): ?>
                        <div class="col-sm-6">
                            <button class="col-sm-4 btn btn-default btn-contact form-control" data-toggle="modal" data-target="#contactModal">Contact</button>
                        </div>

                            <div class="col-sm-6">
                                <?php
                                $html = '<button class=" form-control btn btn-default btn-follow">Become a fan</button>';
                                foreach($user->getFollowedBy() as $fan){
                                    if($fan->getId() == $authdUser->getId()) {
                                        $html = '<button class=" form-control btn btn-default btn-unfollow" data-id="'.$fan['id'].'">Unfan</button>';
                                    }
                                } ?>
                                <?= $html ?>


                            </div>
                        <?php endif; ?>
                    </div>
                <?php endif; ?>
            </div>
            <div class="col-xs-12 col-sm-6">
                <div class="hidden-xs hidden-sm">
                    <h3>Location</h3>
                    <div><?= $user->getCity()->getName().', '.$user->getCity()->getProvince()->getAbbrev() ?></div>
                    <div id="map-canvas"
                         data-lat = "<?=$user->getlatitude() ?>"
                         data-long = "<?=$user->getlongitude() ?>"
                         data-title = "<?=$user->getCity()->getName() ?>"

                        ></div>
                </div>
                <?php if($user->getWebsite()): ?>
                    <h3>Website</h3>
                    <div><a href='<?= $user->getWebsite() ?>' target="_blank"><?= $user->getWebsite() ?></a></div>
                <?php endif; ?>
                <?php if($twitter != null) : ?>
                    <h3>Twitter</h3>
                    <div><a href="http://twitter.com/<?= $twitter['link'] ?>" target="_blank">@<?= $twitter['link'] ?></a></div>
                <?php endif; ?>

            </div>
        </div>

    </div>
    <?php if($authdUser):?>
    <div class="modal fade" id="contactModal">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title">Contact <?= $user->getUsername() ?></h4>
                </div>

                <div class="modal-body">
                    <form role="form">
                        <input type="hidden" class="form-control" id="user_id" value="<?= $authdUser->getId()?>">
                        <input type="hidden" class="form-control" id="video_creator" value="<?= $user->getId()?>">
                        <div class="form-group">
                            <label for="subject">Subject</label>
                            <input type="text" id="subject">
                        </div>
                        <div class="form-group">
                            <label for="message">Message</label>
                            <textarea id="message" class="form-control"></textarea>
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary" id="sendEmail">Send</button>
                </div>
            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->
    <?php endif; ?>
    <div class="col-md-6" id="twitter">
        <?php if(!$twitter) : ?>
            <div class="noTwitter">
                <img src="/img/TSLogo_Full_SML.png" alt="TownSpot"/>
                <?php if($canEdit): ?>
                    <div class="linkTwitter">
                        <h4 class="alert alert-warning">No Twitter Account Linked!</h4>
                    </div>
                <?php endif; ?>
            </div>
        <?php else: ?>
            <a class="twitter-timeline"  href="https://twitter.com/TownSpotTV"
               data-widget-id="460868174456434689"
               data-screen-name="<?= $twitter['link'] ?>"
               data-show-replies="false"
               data-tweet-limit="5">Tweets by @<?= $twitter['link'] ?></a>
            <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
        <?php endif; ?>

    </div>
</div>
<div class="row">
    <div class="col-md-6">
        <h3>About</h3>
        <p><?=$user->getAboutMe()?></p>
    </div>
    <div class="col-md-6" id="interests">
        <h3>Interests</h3>
        <p><?=$user->getInterests()?></p>
    </div>
</div>
<div class="row">
    <div class="col-md-6" id="Comments">
        <div class="row">
            <h3 class="col-xs-12">Comments:</h3>
        </div>
        <?php if($authdUser): ?>
        <div class="row form-group">
            <div class="col-sm-8"><input class='col-sm-8 form-control' placeholder='Leave a Comment' type="text" id="commentText"/></div>
            <div class="col-sm-4">
                <button class="form-control btn btn-primary" id="comment">Comment</button>
            </div>
        </div>
        <?php endif; ?>
        <div class="row">
            <div class="col-xs-12 control-container">
                <?php $class = (count($user->getCommentsAbout()->toArray()) < 5)? ' hidden':'' ?>
                <button class="comment-ctrl prev btn btn-default col-xs-12<?= $class ?>"><i class="fa fa-chevron-up"></i></button>
            </div>
        </div>
        <div class="row list">
            <?php $comments = array_reverse($user->getCommentsAbout()->toArray()); ?>
            <?php foreach($comments as $comment): ?>
                <div class="row col-xs-12 comment" data-id="<?=$comment->getId()?>">
                    <a class="col-xs-2" href="/u/<?=$comment->getUser()->getId()?>">
                        <img class="img-responsive" src="<?= $this->img('user',$comment->getUser()->getId(),100,100)?>" alt="a"/></a>
                    <p class="col-xs-9 offset-xs-1"><?=$comment->getComment()?><br><a href="/u/<?=$comment->getUser()->getId()?>"><?=$comment->getUser()->getUsername()?></a> - <abbr class="timeago" title="<?= $comment->getCreated()->format('Y-m-d H:i:s') ?>"></abbr> <i class="fa fa-times"></i></p>

                </div>
            <?php endforeach; ?>
        </div>
        <div class="row">
            <div class="col-xs-12 control-container">
                <button class="next btn btn-default col-xs-12<?= $class ?>"><i class="fa fa-chevron-down"></i></button>
            </div>
        </div>
    </div>
    <div class="col-md-6" id="fans">
        <?php if (count($user->getFollowedBy())):?>
            <div class="row">
                <h3 class="col-xs-12"><?= (!$canEdit)?$user->getUsername()."'s":'My' ?> Fans (<?= count($user->getFollowedBy()) ?>):</h3>
                <div class="col-xs-1 control-container">
                    <?= (count($user->getFollowedBy()) > 12)?'<i class="fa fa-chevron-left prev"></i>':'' ?>
                </div>
                <div class="col-xs-9 col-sm-10 list">
                    <?php
                    $x = 1;
                    $fanCount = count($user->getFollowedBy());
                    foreach($user->getFollowedBy() as $i => $fan) :?>
                        <?=($x==1)?'<div class="fangroup">':'' ?>
                        <a href="/u/<?=$fan->getId()?>"><img class='col-md-2 col-sm-4 col-xs-6 img-circle' src="<?= $this->img('user',$fan->getId(),100,100)?>" alt="a"/></a>
                        <?=(!($x % 12) || $x == $fanCount)?'</div>':'' ?>
                        <?=(!($x % 12) && $x < $fanCount)?'<div class="fangroup">':'' ?>
                        <?php
                        $x++;
                    endforeach; ?>
                </div>
                <div class="col-xs-1 control-container">
                    <?= (count($user->getFollowedBy()) > 12)?'<i class="fa fa-chevron-right next"></i>':'' ?>
                </div>
            </div>
        <?php endif; ?>
        <?php if (count($user->getFollowing())):?>
            <div class="row">
                <h3 class="col-xs-12">Fan of (<?= count($user->getFollowing()) ?>):</h3>
                <div class="col-xs-1 control-container">
                    <?= (count($user->getFollowing()) > 12)?'<i class="fa fa-chevron-left prev"></i>':'' ?>
                </div>
                <div class="col-sm-10 col-xs-9 list">
                    <?php
                    $x = 1;
                    $fanCount = count($user->getFollowing());
                    foreach($user->getFollowing() as $fan) :?>
                        <?=($x==1)?'<div class="fangroup">':'' ?>
                        <a href="/u/<?=$fan->getId()?>"><img class='col-md-2 col-sm-4 col-xs-6 img-circle' src="<?= $this->img('user',$fan->getId(),100,100)?>" alt="a"/></a>
                        <?=(!($x % 12) || $x == $fanCount)?'</div>':'' ?>
                        <?=(!($x % 12) && $x < $fanCount)?'<div class="fangroup">':'' ?>
                        <?php
                        $x++;
                    endforeach; ?>
                </div>
                <div class="col-xs-1 control-container">
                    <?= (count($user->getFollowing()) > 12)?'<i class="fa fa-chevron-right next"></i>':'' ?>
                </div>
            </div>
        <?php endif; ?>
    </div>
</div>
</div>
<div class="tab-pane" id="events">
    <div class="row">
        <div class="col-sm-12">
            <h1>Events Calendar</h1>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-12">
            <?php if($canEdit): ?>
                <ul class="nav nav-pills">
                    <li><a href="/userevent/create">Create Event</a></li>
                </ul>
            <?php endif; ?>
            <table id='eventsList' class='col-sm-12'>
                <thead>
                <tr class=''>
                    <th>When</th>
                    <th>What</th>
                    <?= $canEdit? "<th class='col-sm-4'>Manage</th>":'' ?>
                </tr>
                </thead>
                <tbody>
                <?php //foreach($user->getUserEvents() as $e): ?>
                <?php foreach(array() as $e): ?>
                    <tr class=''>
                        <td><?= date('M j, Y - g:i a',strtotime($e['UserEvent']['start'])) ?></td>
                        <td>
                            <a data-target='#eventDetails-<?= $e['UserEvent']['id']?>' data-toggle="modal"><?= $e['UserEvent']['title'] ?></a>
                            <div class="modal fade" id="eventDetails-<?= $e['UserEvent']['id'] ?>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                                <div class="modal-dialog">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true"><i class="fa fa-times"></i></i></button>
                                            <h4 class="modal-title" id="myModalLabel">Event Details - <?= $e['UserEvent']['title'] ?></h4>
                                        </div>
                                        <div class="modal-body">
                                            <?php
                                            $eventText = preg_replace("/((https?):((\/\/)|(\\\\))+[\w\d:#@%\/;$()~_?\+-=\\\.&]*)/",'<a href="$1">$1</a>',$e['UserEvent']['description']);
                                            echo $eventText;
                                            ?>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </td>
                        <?php if($canEdit): ?>
                            <td>
                                <a href='/userevent/edit/<?= $e['UserEvent']['id']?>'><i class='fa fa-edit'></i></a>
                                <a href='/userevent/delete/<?= $e['UserEvent']['id']?>'><i class='fa fa-times'></i></a>
                            </td>
                        <?php endif; ?>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>
<div class="tab-pane" id="videos">
    <div class="row">
        <h3 class="col-sm-12"><?= ($canEdit)?'Your':$user->getUsername()."'s" ?> Videos (<span class='videoCount'><?= count($user->getMedia())?></span>):</h3>
    </div>
    <div class="row">&nbsp;</div>
    <div class="list row">
        <?php foreach($user->getMedia() as $v) :?>
            <?php
            $ups = $downs = 0;
            foreach($v->getRatings() as $r) {
                if($r->getRating()) $ups++;
                else $downs++;
            }
            ?>
            <div class="col-sm-6 video">
                <?php if(preg_match('/(?:ytimg)|(?:files)|(?:fbcdn)/',$v->getPreviewImage())): ?>
                    <div class="thumbnail">
                        <a href="<?= $v->getMediaLink() ?>" class="thumb_wrapper bg" style="background-image:
                        url(<?= $v->getPreviewImage() ?>)">&nbsp;</a>
                    </div>
                <?php else: ?>
                    <a href="<?= $v->getMediaLink() ?>" class="thumbnail">
                        <img src="<?= $this->img('video',$v->getId(),720,540) ?>" alt="<?=$v->getTitle()?>">
                    </a>
                <?php endif; ?>

                <div class="caption">
                    <div class="info-button">
                        <div role="button"
                             data-toggle="popover"
                             class="more-info popover-btn"
                             href="#"
                             data-placement="left"
                             data-original-title="<a href='<?= $v->getMediaLink() ?>'><?= htmlentities($v->getTitle()) ?></a> by <a href='<?=$v->getUser()->getProfileLink()?>'><?=$v->getUser()->getDisplayName()?></a>"
                             data-content="<div class='location'><?= $v->getCity()->getName() ?>, <?= $v->getProvince()->getName() ?></div><div class='text'><?= $v->getLogline()?></div>
                                    <footer>
                                    <span class='video-duration'><i class='fa fa-clock-o'></i> <?= $v->getDuration()?></span>
                                    <span class='video-plays'><i class='fa fa-play'></i> <?=number_format($v->getViews())?></span>
                                    <span class='video-thumbs-up'><i class='fa fa-thumbs-up'></i> <?=$ups ?></span>
                                    <span class='video-thumbs-down'><i class='fa fa-thumbs-down'></i> <?= $downs ?></span>
                                    <span class='video-comments'><i class='fa fa-comments'></i> <?=count($v->getCommentsAbout()) ?></span>
                                    </footer>"
                            >
                            <i class="fa fa-info-circle"></i>
                        </div>
                    </div>
                    <h4><a href="<?= $v->getMediaLink() ?>"><?=$v->getTitle()?></a></h4>
                    <?php $time = $v->getDebutTime()->getTimeStamp() + $TZoffset; ?>
                    <?php $time = date('F jS, Y', $time); ?>
                    <h4>Premiered on <?= $time; ?></h4>
                </div>

            </div>
            <?php if($canEdit): ?>
                <div class="col-md-6 stats">
                    <h4>Video Statistics</h4>
                    <dl class="dl-horizontal">
                        <dt>Views</dt>
                        <dd><?=number_format($v->getViews())?></dd>
                        <dt>Likes</dt>
                        <dd><?=$ups?></dd>
                        <dt>Dislikes</dt>
                        <dd><?=$downs?></dd>
                    </dl>
                    <h4>Video Actions</h4>
                    <ul class="list-unstyled" data-id="<?=$v->getId()?>">
                        <li class="delete"><i class="fa fa-times"></i> Delete</li>
                        <li class="edit"><i class="fa fa-pencil"></i> Edit</li>
                    </ul>
                </div>
            <?php endif; ?>
        <?php endforeach; ?>
    </div>
</div>
<?php if ($canEdit): ?>
    <div class="tab-pane" id="favorites">
        <div class="row">
            <h3 class="col-sm-12"><?= ($canEdit)?'Your':$user->getUsername()."'s" ?> Favorite Videos:</h3>
        </div>
        <?php if (count($user->getFavorites()) > 8): ?>
            <!-- div class="row">
                <div class="col-sm-12">
                    <button class="btn btn-primary form-control prev">
                        <i class="fa fa-chevron-up"></i>
                    </button>
                </div>
            </div -->
        <?php endif; ?>
        <div class="list">
            <?php //var_dump($user->getFavorites()); ?>
            <?php foreach($user->getFavorites() as $k => $v) :?>
                <div class="col-sm-6 video" data-id="<?=$v->getId()?>" data-key="<?=$k ?>">
                    <a href="/videos/<?=$v->getId()?>/<?= urlencode($v->getTitle())?>" class="thumbnail">
                        <img src="<?= $this->img('video',$v->getId(),720,540) ?>" alt="<?=$v->getTitle()?>">
                    </a>

                    <div class="caption">
                        <h4><a href="<?= $v->getMediaLink() ?>"><?=$v->getTitle()?></a></h4>
                        <div class="info-button">
                            <div role="button"
                                 data-placement="left"
                                 data-toggle="popover"
                                 class="more-info popover-btn" href="#"
                                 data-original-title="<a href='<?= $v->getMediaLink() ?>'><?= htmlentities($v->getTitle()) ?></a> by <a href='<?=$v->getUser()->getProfileLink()?>'><?=$v->getUser()->getDisplayName()?></a>"
                                 data-content="<div class='location'><?= $v->getCity()->getName() ?>, <?= $v->getProvince()->getName() ?></div><div class='text'><?= $v->getLogline()?></div>
                                    <footer>
                                    <span class='video-duration'><i class='fa fa-clock-o'></i> <?= $v->getDuration()?></span>
                                    <span class='video-plays'><i class='fa fa-play'></i> <?=number_format($v->getViews());?></span>
                                    <span class='video-thumbs-up'><i class='fa fa-thumbs-up'></i> <?=$ups ?></span>
                                    <span class='video-thumbs-down'><i class='fa fa-thumbs-down'></i> <?= $downs ?></span>
                                    <span class='video-comments'><i class='fa fa-comments'></i> <?=count($v->getCommentsAbout()) ?></span>
                                    </footer>"
                            >
                                <i class="fa fa-info-circle"></i>
                            </div>
                        </div>

                        <?php if($canEdit) : ?>
                            <a href="javascript:void()" class="unfav"><i class="fa fa-times-circle"></i></a>
                        <?php endif; ?>
                    </div>

                </div>
            <?php endforeach; ?>
        </div>
        <?php if (count($user->getFavorites()) > 8): ?>
            <!-- div class="row">
                <div class="col-sm-12">
                    <button class="btn btn-primary form-control next">
                        <i class="fa fa-chevron-down"></i>
                    </button>
                </div>
            </div -->
        <?php endif; ?>
    </div>
<?php endif; ?>
</div>
</div>
<script>
    $(function() {
        var hash = window.location.hash;
        hash && $('ul.nav a[href="' + hash + '"]').tab('show');
    });
    $(document).ready(
        $().UserProfile({
            username: '<?= $authdUser?$authdUser->getUsername():''; ?>',
            follower_id: <?= $authdUser? $authdUser->getId():'' ?>,
            followee_id: <?= $user->getId()?>,
            share_email: '<?= $user->getAllowContact() ?>'
        })
    );
</script>
<script type="text/javascript"
        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCa1RYJsf-C94cTQo34GC59DkiijUq_54s&sensor=true">
</script>
<script type="text/javascript">

    var lat = $('#map-canvas').attr('data-lat');
    if(!lat) lat = 0;
    var long = $('#map-canvas').attr('data-long');
    if (!long) long = 0;
    var markerTitle = $('#map-canvas').attr('data-title');
    if (!markerTitle) markerTitle = 'no data';
    function initialize() {
        var myLatlng = new google.maps.LatLng(lat,long);
        var mapOptions = {
            center: myLatlng,
            zoom: 8
        };
        var map = new google.maps.Map(document.getElementById("map-canvas"),
            mapOptions);

        var marker = new google.maps.Marker({
            position: myLatlng,
            map: map,
            title:markerTitle
        });
    }
    google.maps.event.addDomListener(window, 'load', initialize);

</script>