<div class="container" id="userProfile">
<div class="row">
    <div class="col-sm-4 hidden-xs" id="username">
        <?= $user->getUsername()?>
    </div>
    <div class="col-sm-8">
        <ul class="nav nav-pills pull-right">
            <?php if ($canEdit): ?>
                <li><a href="/users/manageseries">Manage My Series</a></li>
            <?php endif; ?>
            <li class="active"><a href="#profile" data-toggle="tab">Profile</a></li>
            <!-- <li><a href="#events" data-toggle="tab">Events</a></li> -->
            <li><a href="#videos" data-toggle="tab">Videos</a></li>
            <?php if($canEdit): ?>
                <li><a href="#favorites" data-toggle="tab">Favorites</a></li>
            <?php endif; ?>
        </ul>
    </div>

</div>
<div class="tab-content">
<div class="tab-pane active" id="profile">
<div class="row">

    <div class="col-sm-6" id="userDetails">
        <div class="row edit">
            <div class="col-sm-12">
                <?php if($canEdit) : ?><a href="/users/edit"><i class="fa fa-edit pull-right"></i></a><?php endif; ?>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-6">
                <img class='profile-pic img-responsive' src="<?= $this->img('user',$user->getId(),260) ?>" alt="a"/>
                <h3>Username</h3>
                <div><?= $user->getUsername() ?></div>
                <?php if ($canEdit) : ?>
                    <h3>Email</h3>
                    <div><?= $user->getEmail() ?></div>
                <?php elseif($user->getAllowContact()): ?>
                    <div class="row">
                        &nbsp;
                    </div>
                    <div class="row">
                        <div class="col-sm-6">
                            <button class="col-sm-4 btn btn-default btn-contact form-control" data-toggle="modal" data-target="#contactModal">Contact</button>
                        </div>
                        <?php if(!$canEdit): ?>
                            <div class="col-sm-6">
                                <?php
                                $html = '<button class=" form-control btn btn-default btn-follow">Become a fan</button>';
                                foreach($user->getFollowedBy() as $fan){
                                    if($fan->getId() == $authdUser) {
                                        $html = '<button class=" form-control btn btn-default btn-unfollow" data-id="'.$fan['id'].'">Unfan</button>';
                                    }
                                } ?>
                                <?= $html ?>


                            </div>
                        <?php endif; ?>
                    </div>
                <?php endif; ?>

            </div>
            <div class="col-xs-12 col-sm-6">
                <h3>Location</h3>
                <div><?= $user->getCity()->getName().', '.$user->getCity()->getProvince()->getAbbrev() ?></div>
                <div id="map-canvas"
                     data-lat = "<?=$user->getlatitude() ?>"
                     data-long = "<?=$user->getlongitude() ?>"
                     data-title = "<?=$user->getCity()->getName() ?>"

                    ></div>
                <?php if($user->getWebsite()): ?>
                    <h3>Website</h3>
                    <div><a href='<?= $user->getWebsite() ?>' target="_blank"><?= $user->getWebsite() ?></a></div>
                <?php endif; ?>
                <?php if(!empty($tweets)) : ?>
                    <h3>Twitter</h3>
                    <div><a href="http://twitter.com/<?= $user['User']['twitter'] ?>" target="_blank">@<?= $user['User']['twitter'] ?></a></div>
                <?php endif; ?>
            </div>
        </div>

    </div>

    <div class="modal fade" id="contactModal">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title">Contact <?= $user->getUsername() ?></h4>
                </div>
                <div class="modal-body">
                    <form role="form">
                        <input type="hidden" class="form-control" id="user_id" value="<?= $authdUser?>">
                        <input type="hidden" class="form-control" id="video_creator" value="<?= $user->getId()?>">
                        <div class="form-group">
                            <label for="subject">Subject</label>
                            <input type="text" id="subject">
                        </div>
                        <div class="form-group">
                            <label for="message">Message</label>
                            <textarea id="message" class="form-control"></textarea>
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary" id="sendEmail">Send</button>
                </div>
            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->
    <div class="col-md-6" id="twitter">
        <?php if(empty($tweets)) : ?>
            <div class="noTwitter">
                <img src="/img/TSLogo_Full_SML.png" alt="TownSpot"/>
                <?php if($canEdit): ?>
                    <div class="linkTwitter">
                        <h4 class="alert alert-warning">No Twitter Account Linked!</h4>
                    </div>
                <?php endif; ?>
            </div>
        <?php else: ?>
        <a class="twitter-timeline" href="https://twitter.com/tatiana"
            <a class="twitter-timeline"  href="https://twitter.com/TownSpotTV"
               data-widget-id="460868174456434689"
               data-screen-name="<?=$user['User']['twitter']?>"
               data-show-replies="false"
               data-tweet-limit="5">Tweets by @<?=$user['User']['twitter']?></a>
            <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
        <?php endif; ?>

    </div>
</div>
<div class="row">
    <div class="col-md-6">
        <h3>About</h3>
        <p><?=$user->getAboutMe()?></p>
    </div>
    <div class="col-md-6" id="interests">
        <h3>Interests</h3>
        <p><?=$user->getInterests()?></p>
    </div>
</div>
<div class="row">
    <div class="col-md-6" id="Comments">
        <div class="row">
            <h3 class="col-xs-12">Comments:</h3>
        </div>
        <div class="row form-group">
            <div class="col-sm-8"><input class='col-sm-8 form-control' placeholder='Leave a Comment' type="text" id="commentText"/></div>
            <div class="col-sm-4">
                <button class="form-control btn btn-primary" id="comment">Comment</button>
            </div>

        </div>
        <div class="row">
            <div class="col-xs-12 control-container">
                <?= (count($user->getCommentsAbout()) > 5)?'<button class="prev btn btn-default col-xs-12"><i class="fa fa-chevron-up"></i></button>':'' ?>
            </div>
        </div>
        <div class="row list">

            <?php foreach($user->getCommentsAbout() as $comment): ?>
                <div class="row col-xs-12 comment">
                    <a class="col-xs-2" href="/u/<?=$comment['user_id']?>"><img class="img-responsive" src="<?= $this->img('user',$comment['user_id'],100,100)?>" alt="a"/></a>
                    <?php $time = strtotime($comment['created']) + $TZoffset; ?>
                    <?php $time = date('Y-m-d H:i:s', $time); ?>
                    <p class="col-xs-9 offset-xs-1"><?=$comment['comment']?><br><a href="/u/<?=$comment['user_id']?>"><?=$comment['Commenter']['username']?></a> - <abbr class="timeago" title="<?= $time ?>"></abbr></p>
                </div>
            <?php endforeach; ?>
        </div>
        <div class="row">
            <div class="col-xs-12 control-container">
                <?= (count($user->getCommentsAbout()) > 5)?'<button class="next btn btn-default col-xs-12"><i class="fa fa-chevron-down"></i></button>':'' ?>
            </div>
        </div>
    </div>
    <div class="col-md-6" id="fans">
        <?php if (count($user->getFollowedBy())):?>
            <div class="row">
                <h3 class="col-xs-12"><?= (!$canEdit)?$user->getUsername()."'s":'My' ?> Fans (<?= count($user->getFollowedBy()) ?>):</h3>
                <div class="col-xs-1 control-container">
                    <?= (count($user->getFollowedBy()) > 12)?'<i class="fa fa-chevron-left prev"></i>':'' ?>
                </div>
                <div class="col-xs-9 col-sm-10 list">
                    <?php
                    $x = 1;
                    $fanCount = count($user->getFollowedBy());
                    foreach($user->getFollowedBy() as $i => $fan) :?>
                        <?=($x==1)?'<div class="fangroup">':'' ?>
                        <a href="/u/<?=$fan->getId()?>"><img class='col-md-2 col-sm-4 col-xs-6 img-circle' src="<?= $this->img('user',$fan->getId(),100,100)?>" alt="a"/></a>
                        <?=(!($x % 12) || $x == $fanCount)?'</div>':'' ?>
                        <?=(!($x % 12) && $x < $fanCount)?'<div class="fangroup">':'' ?>
                        <?php
                        $x++;
                    endforeach; ?>
                </div>
                <div class="col-xs-1 control-container">
                    <?= (count($user->getFollowedBy()) > 12)?'<i class="fa fa-chevron-right next"></i>':'' ?>
                </div>
            </div>
        <?php endif; ?>
        <?php if (count($user->getFollowing())):?>
            <div class="row">
                <h3 class="col-xs-12">Fan of (<?= count($user->getFollowing()) ?>):</h3>
                <div class="col-xs-1 control-container">
                    <?= (count($user->getFollowing()) > 12)?'<i class="fa fa-chevron-left prev"></i>':'' ?>
                </div>
                <div class="col-sm-10 col-xs-9 list">
                    <?php
                    $x = 1;
                    $fanCount = count($user->getFollowing());
                    foreach($user->getFollowing() as $fan) :?>
                        <?=($x==1)?'<div class="fangroup">':'' ?>
                        <a href="/u/<?=$fan->getId()?>"><img class='col-md-2 col-sm-4 col-xs-6 img-circle' src="<?= $this->img('user',$fan->getId(),100,100)?>" alt="a"/></a>
                        <?=(!($x % 12) || $x == $fanCount)?'</div>':'' ?>
                        <?=(!($x % 12) && $x < $fanCount)?'<div class="fangroup">':'' ?>
                        <?php
                        $x++;
                    endforeach; ?>
                </div>
                <div class="col-xs-1 control-container">
                    <?= (count($user->getFollowing()) > 12)?'<i class="fa fa-chevron-right next"></i>':'' ?>
                </div>
            </div>
        <?php endif; ?>
    </div>
</div>
</div>
<div class="tab-pane" id="events">
    <div class="row">
        <div class="col-sm-12">
            <h1>Events Calendar</h1>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-12">
            <?php if($canEdit): ?>
                <ul class="nav nav-pills">
                    <li><a href="/userevent/create">Create Event</a></li>
                </ul>
            <?php endif; ?>
            <table id='eventsList' class='col-sm-12'>
                <thead>
                <tr class=''>
                    <th>When</th>
                    <th>What</th>
                    <?= $canEdit? "<th class='col-sm-4'>Manage</th>":'' ?>
                </tr>
                </thead>
                <tbody>
                <?php //foreach($user->getUserEvents() as $e): ?>
                <?php foreach(array() as $e): ?>
                    <tr class=''>
                        <td><?= date('M j, Y - g:i a',strtotime($e['UserEvent']['start'])) ?></td>
                        <td>
                            <a data-target='#eventDetails-<?= $e['UserEvent']['id']?>' data-toggle="modal"><?= $e['UserEvent']['title'] ?></a>
                            <div class="modal fade" id="eventDetails-<?= $e['UserEvent']['id'] ?>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                                <div class="modal-dialog">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true"><i class="fa fa-times"></i></i></button>
                                            <h4 class="modal-title" id="myModalLabel">Event Details - <?= $e['UserEvent']['title'] ?></h4>
                                        </div>
                                        <div class="modal-body">
                                            <?php
                                            $eventText = preg_replace("/((https?):((\/\/)|(\\\\))+[\w\d:#@%\/;$()~_?\+-=\\\.&]*)/",'<a href="$1">$1</a>',$e['UserEvent']['description']);
                                            echo $eventText;
                                            ?>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </td>
                        <?php if($canEdit): ?>
                            <td>
                                <a href='/userevent/edit/<?= $e['UserEvent']['id']?>'><i class='fa fa-edit'></i></a>
                                <a href='/userevent/delete/<?= $e['UserEvent']['id']?>'><i class='fa fa-times'></i></a>
                            </td>
                        <?php endif; ?>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>
<div class="tab-pane" id="videos">
    <div class="row">
        <h3 class="col-sm-12"><?= ($canEdit)?'Your':$user->getUsername()."'s" ?> Videos (<?= count($user->getMedia())?>):</h3>
    </div>
    <div class="row">&nbsp;</div>
    <div class="list row">
        <?php foreach($user->getMedia() as $v) :?>
            <?php
                $ups = $downs = 0;
                foreach($v->getRatings() as $r) {
                    if($r->getRating()) $ups++;
                    else $downs++;
                }
            ?>
            <div class="col-sm-6 video">
                <a href="/videos/<?=$v->getId()?>/<?= urlencode($v->getTitle())?>" class="thumbnail">
                    <?php if(preg_match('/ytimg/',$v->getPreviewImage())): ?>
                        <img class="img-responsive" src="<?= $v->getPreviewImage() ?>" alt="<?=$v->getTitle()?>">
                    <?php else: ?>
                        <img src="<?= $this->img('video',$v->getId(),720,540) ?>" alt="<?=$v->getTitle()?>">
                    <?php endif; ?>
                </a>

                <div class="caption">
                    <div class="info-button">
                        <div role="button"
                             data-content="<?= $v->getCity()->getName() ?>, <?= $v->getProvince()->getName() ?><br/><?= $v->getLogLine()?>"
                             data-toggle="popover"
                             class="more-info popover-btn"
                             href="#"
                             data-title="<?= $v->getTitle()?>"
                             data-placement="left"
                             data-footer="
                                        <span class='video-duration'>
                                            <i class='fa fa-clock-o'></i>
                                            <?=$v->getDuration()?>
                                        </span>
                                        <span class='video-plays'>
                                            <i class='fa fa-play'></i>
                                            <?=$v->getViews()?>
                                        </span>
                                        <span class='video-thumbs-up'>
                                            <i class='fa fa-thumbs-up'></i>
                                            <?= $ups ?>
                                        </span>
                                        <span class='video-thumbs-down'>
                                            <i class='fa fa-thumbs-down'></i>
                                            <?= $downs ?></span>
                                        <span class='video-comments'>
                                            <i class='fa fa-comments'></i>
                                            <?=count($v->getCommentsAbout())?>
                                        </span>
							        ">
                            <i class="fa fa-info-circle"></i>
                        </div>
                    </div>
                    <h4><a href="/videos/<?=$v->getId()?>/<?= urlencode($v->getTitle())?>"><?=$v->getTitle()?></a></h4>
                    <?php $time = $v->getDebutTime()->getTimeStamp() + $TZoffset; ?>
                    <?php $time = date('F jS, Y', $time); ?>
                    <h4>Premiered on <?= $time; ?></h4>
                </div>

            </div>
            <?php if($canEdit): ?>
                <div class="col-md-6 stats">
                    <h4>Video Statistics</h4>
                    <dl class="dl-horizontal">
                        <dt>Views</dt>
                        <dd><?=$v->getViews()?></dd>
                        <dt>Likes</dt>
                        <dd><?=$ups?></dd>
                        <dt>Dislikes</dt>
                        <dd><?=$downs?></dd>
                    </dl>
                    <h4>Video Actions</h4>
                    <ul class="list-unstyled">
                        <li class="delete"><i class="fa fa-times"></i> Delete</li>
                        <li class="edit"><i class="fa fa-pencil"></i> Edit</li>
                    </ul>
                </div>
            <?php endif; ?>
        <?php endforeach; ?>
    </div>
</div>
<?php if ($canEdit): ?>
    <div class="tab-pane" id="favorites">
        <div class="row">
            <h3 class="col-sm-12"><?= ($canEdit)?'Your':$user->getUsername()."'s" ?> Favorite Videos:</h3>
        </div>
        <?php if (count($user->getFavorites()) > 8): ?>
            <!-- div class="row">
                <div class="col-sm-12">
                    <button class="btn btn-primary form-control prev">
                        <i class="fa fa-chevron-up"></i>
                    </button>
                </div>
            </div -->
        <?php endif; ?>
        <div class="list">
            <?php //var_dump($user->getFavorites()); ?>
            <?php foreach($user->getFavorites() as $v) :?>
                <div class="col-sm-6 video" data-id="<?=$v->getId()?>">
                    <a href="/videos/<?=$v->getId()?>/<?= urlencode($v->getTitle())?>" class="thumbnail">
                        <img src="<?= $this->img('video',$v->getId(),720,540) ?>" alt="<?=$v->getTitle()?>">
                    </a>

                    <div class="caption">
                        <div class="info-button">
                            <div role="button" data-placement="left" data-content="<?= $v->getCity()->getName() ?>, <?= $v->getProvince()->getName() ?><br/><?= $v->getLogline()?>" data-toggle="popover" class="more-info popover-btn" href="#" data-title="<?= $v->getTitle()?>" data-footer="<span class='video-duration'><i class='fa fa-clock-o'></i> <?= $v->getDuration()?></span> <span class='video-plays'><i class='fa fa-play'></i> <?=$v->getViews()?></span> <span class='video-thumbs-up'><i class='fa fa-thumbs-up'></i> <?=$ups ?></span> <span class='video-thumbs-down'><i class='fa fa-thumbs-down'></i> <?= $downs ?></span> <span class='video-comments'><i class='fa fa-comments'></i> <?=count($v->getCommentsAbout()) ?></span>"><i class="fa fa-info-circle"></i></div>
                        </div>
                        <h4><a href="/videos/<?=$v->getId()?>/<?= urlencode($v->getTitle())?>"><?=$v->getTitle()?></a></h4>
                        <?php if($canEdit) : ?>
                            <a href="javascript:void()" class="unfav"><i class="fa fa-times-circle"></i></a>
                        <?php endif; ?>
                    </div>

                </div>
            <?php endforeach; ?>
        </div>
        <?php if (count($user->getFavorites()) > 8): ?>
            <!-- div class="row">
                <div class="col-sm-12">
                    <button class="btn btn-primary form-control next">
                        <i class="fa fa-chevron-down"></i>
                    </button>
                </div>
            </div -->
        <?php endif; ?>
    </div>
<?php endif; ?>
</div>
</div>
<script>
    $(function() {
        var hash = window.location.hash;
        hash && $('ul.nav a[href="' + hash + '"]').tab('show');
    });
    $(document).ready(
        $().UserProfile({
            follower_id: <?= $authdUser ?>,
            followee_id: <?= $user->getId()?>,
            share_email: '<?= $user->getAllowContact() ?>'
        })
    );
</script>