<div class="container users form" id="manage-series">
    <div class="col-sm-12">
        <ul class="nav nav-pills pull-right">
            <li class="active"><a href="/users/manageseries">Manage My Series</a></li>
            <li><a href="/dashboard#profile">Profile</a></li>
            <!-- <li><a href="#events" data-toggle="tab">Events</a></li> -->
            <li><a href="/dashboard#videos">Videos</a></li>
            <li><a href="/dashboard#favorites">Favorites</a></li>
        </ul>
    </div>
    <div class="row">
        <h3 class="col-sm-12">
            Create Series
        </h3>
    </div>
    <div class="row">
        <form class="townspot-form">
            <div class="col-sm-11">
                <input name="title" class="title input-lg form-control" type="text">
            </div>
            <div class="col-sm-1">
                <button class="add btn btn-primary btn-lg "><i class="fa fa-plus"></i></button>
            </div>
        </form>
    </div>

    <div class="row">
        <div class="col-sm-6">
            <h3>Your Series</h3>
            <ul class="series-list list-unstyled">

            </ul>
        </div>
        <div class="col-sm-6">
            <h3>Available Videos</h3>
            <ul class="available-video-list  list-unstyled">

            </ul>
        </div>
    </div>
</div>
<script>
    $().Series({
        user_id: <?= $user->getId() ?>
    });
</script>