<div class="advertisement-title">advertisement</div>
<script type="text/javascript"><!--
google_ad_client = "ca-<?= $this->ad->getPublisherId(); ?>";
google_ad_slot = "<?= $this->ad->getId(); ?>";
google_ad_width = <?= $this->ad->getWidth(); ?>;
google_ad_height = <?= $this->ad->getHeight(); ?>;
//-->
</script>
<script type="text/javascript"
src="//pagead2.googlesyndication.com/pagead/show_ads.js">
</script>