<script src="/js/home.js"></script>
<div class="row hidden-xs">
	<div class="col-sm-12">
		<h1>On Screen Today</h1>	
	</div>
</div>
<div class="row wide-carousel">
	<div class="col-sm-12 wide-carousel-row">
		<div data-ride="carousel" class="col-sm-12 carousel slide" id="on-stage-carousel">
			<div id="on-stage-carousel-inner" class="carousel-inner"></div>
			<a class="left carousel-control on-stage-carousel-control" href="#on-stage-carousel" data-slide="prev">
				<img src="/img/slide-left.gif">
			</a>
			<a class="right carousel-control on-stage-carousel-control" href="#on-stage-carousel" data-slide="next">
				<img src="/img/slide-right.gif">
			</a>		
			<ol class="carousel-indicators">
<?php for ($i=0; $i < $this->onScreenCount; $i++) { ?>
				<li class="<?= ($i == 0) ? "active" : ""; ?>" data-slide-to="<?= $i; ?>" data-target="#on-stage-carousel"></li>
<?php } ?>
			</ol>
		</div>
	</div>
</div>
<div class="container">

<div class="row wide-carousel" id="DH">
	<div class="col-sm-12">
		<h1>Daily Highlights</h1>	
	</div>
</div>
<div class="row" id="DHContent">
	<div class="col-sm-12">
		<div data-ride="carousel" class="carousel slide" id="daily-hightlights-carousel">
			<div class="carousel-inner" id="daily-hightlights-carousel-inner"></div>
			<a data-slide="prev" href="#daily-hightlights-carousel" class="left carousel-control">
				<i class="fa fa-chevron-left fa-stack-1x"></i>
			</a>
			<a data-slide="next" href="#daily-hightlights-carousel" class="right carousel-control">
				<i class="fa fa-chevron-right fa-stack-1x"></i>
			</a>
			<ol class="carousel-indicators" id="daily-hightlights-carousel-indicators"></ol>
		</div>
	</div>
</div>	
<div class="row">
	<div class="col-sm-12">
		<h1>Staff Favorites</h1>	
	</div>
</div>
<div class="row">
	<div class="col-sm-12">
		<div data-ride="carousel" class="carousel slide" id="staff-favorites-carousel">
			<div class="carousel-inner" id="staff-favorites-carousel-inner"></div>
			<a data-slide="prev" href="#staff-favorites-carousel" class="left carousel-control">
				<i class="fa fa-chevron-left fa-stack-1x"></i>
			</a>
			<a data-slide="next" href="#staff-favorites-carousel" class="right carousel-control">
				<i class="fa fa-chevron-right fa-stack-1x"></i>
			</a>
			<ol class="carousel-indicators" id="staff-favorites-carousel-indicators"></ol>
		</div>
	</div>
</div>	
</div>

<div class="row ad-panel">
	<div class="col-xs-12 google-ad" data-position="leaderboard" ></div>
</div>		
<?= $this->partial('partials/backbone/video-template.phtml'); ?>
<?= $this->partial('partials/backbone/carousel-row-template.phtml'); ?>
<?= $this->partial('partials/backbone/carousel-video.phtml'); ?>
<?= $this->partial('partials/backbone/carousel-indicator-template.phtml'); ?>
<script>
$(function(){

	var onScreen_media 								= <?= $onScreen; ?>;
    var onScreen_media_collection			 		= new VideoCollection();		
    $.each(onScreen_media, function() 				{	onScreen_media_collection.add(new Video(this));		});
    var onScreen_media_view 						= new VideoView({el: 		'#on-stage-carousel-inner'});		
	onScreen_media_view.setTemplate('#carousel-video');
    onScreen_media_view.renderCarouselCollection(onScreen_media_collection);

	var dailyHighlights_media 						= <?= $dailyHighlights; ?>;
    var dailyHighlights_media_collection			= new VideoCollection();		
    $.each(dailyHighlights_media, function() 		{	dailyHighlights_media_collection.add(new Video(this));		});
    var dailyHighlights_media_view					= new VideoView({el: 		'#daily-hightlights-carousel-inner'});		
    var dailyHighlights_media_carousel_view			= new VideoView({el: 		'#daily-hightlights-carousel-indicators'});		
	dailyHighlights_media_view.setTemplate('#carousel-row-template');
	dailyHighlights_media_carousel_view.setTemplate('#carousel-indicator-template');

	var staffFavorites_media 						= <?= $staffFavorites; ?>;
    var staffFavorites_media_collection				= new VideoCollection();		
    $.each(staffFavorites_media, function() 		{	staffFavorites_media_collection.add(new Video(this));		});
    var staffFavorites_media_view					= new VideoView({el: 		'#staff-favorites-carousel-inner'});		
    var staffFavorites_media_carousel_view			= new VideoView({el: 		'#staff-favorites-carousel-indicators'});		
	staffFavorites_media_view.setTemplate('#carousel-row-template');
	staffFavorites_media_carousel_view.setTemplate('#carousel-indicator-template');

	if ( $(window).width() > 768) {      
		dailyHighlights_media_view.renderCarouselRow(dailyHighlights_media_collection,3);
		dailyHighlights_media_carousel_view.renderCarouselRowIndicators('daily-hightlights-carousel',dailyHighlights_media_collection,3);
		staffFavorites_media_view.renderCarouselRow(staffFavorites_media_collection,3);
		staffFavorites_media_carousel_view.renderCarouselRowIndicators('staff-favorites-carousel',staffFavorites_media_collection,3);
	} else if ( $(window).width() > 600) {      
		dailyHighlights_media_view.renderCarouselRow(dailyHighlights_media_collection,2);
		dailyHighlights_media_carousel_view.renderCarouselRowIndicators('daily-hightlights-carousel',dailyHighlights_media_collection,2);
		staffFavorites_media_view.renderCarouselRow(staffFavorites_media_collection,2);
		staffFavorites_media_carousel_view.renderCarouselRowIndicators('staff-favorites-carousel',staffFavorites_media_collection,2);
	} else {
		dailyHighlights_media_view.renderCarouselRow(dailyHighlights_media_collection,1);
		dailyHighlights_media_carousel_view.renderCarouselRowIndicators('daily-hightlights-carousel',dailyHighlights_media_collection,1);
		staffFavorites_media_view.renderCarouselRow(staffFavorites_media_collection,1);
		staffFavorites_media_carousel_view.renderCarouselRowIndicators('staff-favorites-carousel',staffFavorites_media_collection,1);
	}
	
	setInfoButtons();

	$('#on-stage-carousel').carousel({	interval: 70000	});
	$('#daily-hightlights-carousel').carousel({	interval: false	});
	$('#staff-favorites-carousel').carousel({	interval: false	});
		
	$(window).bind('resolutionchange', function(){
		if ( $(window).width() > 768) {      
			dailyHighlights_media_view.renderCarouselRow(dailyHighlights_media_collection,3);
			dailyHighlights_media_carousel_view.renderCarouselRowIndicators('daily-hightlights-carousel',dailyHighlights_media_collection,3);
			staffFavorites_media_view.renderCarouselRow(staffFavorites_media_collection,3);
			staffFavorites_media_carousel_view.renderCarouselRowIndicators('staff-favorites-carousel',staffFavorites_media_collection,3);
		} else if ( $(window).width() > 600) {      
			dailyHighlights_media_view.renderCarouselRow(dailyHighlights_media_collection,2);
			dailyHighlights_media_carousel_view.renderCarouselRowIndicators('daily-hightlights-carousel',dailyHighlights_media_collection,2);
			staffFavorites_media_view.renderCarouselRow(staffFavorites_media_collection,2);
			staffFavorites_media_carousel_view.renderCarouselRowIndicators('staff-favorites-carousel',staffFavorites_media_collection,2);
		} else {
			dailyHighlights_media_view.renderCarouselRow(dailyHighlights_media_collection,1);
			dailyHighlights_media_carousel_view.renderCarouselRowIndicators('daily-hightlights-carousel',dailyHighlights_media_collection,1);
			staffFavorites_media_view.renderCarouselRow(staffFavorites_media_collection,1);
			staffFavorites_media_carousel_view.renderCarouselRowIndicators('staff-favorites-carousel',staffFavorites_media_collection,1);
		}
		setInfoButtons();
	});
});

$(document).ready(function(){
	var $highlights = $("#daily-hightlights-carousel");
	var $staffFavorites = $("#staff-favorites-carousel");

	var hammer_highlights = new Hammer($highlights[0]);
	var hammer_staff = new Hammer($staffFavorites[0]);

	hammer_highlights.on('panleft swipeleft',function(){
		$highlights.find('.fa-chevron-right').click();
	});

	hammer_highlights.on('panright swiperight',function(){
                $highlights.find('.fa-chevron-left').click();
        });

	hammer_staff.on('panleft swipeleft',function(){
                $staffFavorites.find('.fa-chevron-right').click();
        });

        hammer_staff.on('panright swiperight',function(){
                $staffFavorites.find('.fa-chevron-left').click();
        });

	$('#daily-highlights-carousel-inner .item.active .row:first .col-xs-12').attr('id','slot1target');


	var slotUser = 0;
	<?php if($this->zfcUserIdentity()) : ?>
		slotUser = <?= $this->zfcUserIdentity()->getId() ?>
	<?php endif; ?>

	var slotmedia = '';

	if(slotUser) {
		$.get('/api/media/slot1/2',function(response){
			slotmedia = response.data;

			var slotmedia_collection = new VideoCollection();
			var slotmedia_view = new VideoView({el: '#slottarget'});

			$.each(slotmedia,function(){slotmedia_collection.add(new Video(this))});

			$('#slottarget').children().remove();

			slotmedia_view.render(slotmedia_collection);
		});
	}
});

</script>
