<div class="row hidden-xs">
	<div class="col-sm-12">
		<h1>On Screen Today</h1>	
	</div>
</div>
<div class="row">
	<div class="col-sm-12">
		<h1>Daily Highlights</h1>	
	</div>
</div>
<div class="row">
	<div class="col-sm-12 wide-carousel">
		<?= $this->VideoCarousel($dailyHighlights,array(
			'id' => 'highlights-lg',
			'per_panel' => 3,
			'class' => 'hidden-xs hidden-xxs'
			)); ?>
		<?= $this->VideoCarousel($dailyHighlights,array(
			'id' => 'highlights-sm',
			'per_panel' => 2,
			'class' => 'visible-xs'
			)); ?>
		<?= $this->VideoCarousel($dailyHighlights,array(
			'id' => 'highlights-xs',
			'per_panel' => 1,
			'class' => 'visible-xxs'
			)); ?>
	</div>
</div>
<div class="row">
	<div class="col-sm-12">
		<h1>Staff Favorites</h1>	
	</div>
</div>
<div class="row">
	<div class="col-sm-12 wide-carousel">
		<?= $this->VideoCarousel($staffFavorites,array(
			'id' => 'favorites-lg',
			'per_panel' => 3,
			'class' => 'hidden-xs hidden-xxs'
			)); ?>
		<?= $this->VideoCarousel($staffFavorites,array(
			'id' => 'favorites-sm',
			'per_panel' => 2,
			'class' => 'visible-xs'
			)); ?>
		<?= $this->VideoCarousel($staffFavorites,array(
			'id' => 'favorites-xs',
			'per_panel' => 1,
			'class' => 'visible-xxs'
			)); ?>
	</div>
</div>
<br/>
<br/>
<br/>
