<?php
$form = $this->loginForm;
$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/login'));
$form->setAttribute('method', 'post');
?>

<?php echo $this->form()->openTag($form) ?>
<?php echo $this->formElementErrors($form->get('identity')) ?>
<div class="form-group"><?php echo $this->formInput($form->get('identity')) ?></div>
<div class="form-group"><?php echo $this->formInput($form->get('credential')) ?></div>

<?php if ($this->redirect): ?>
    <input type="hidden" name="redirect" value="<?php echo $this->escapeHtml($this->redirect) ?>" />
<?php endif ?>

<?php echo $this->formButton($form->get('submit')) ?>

<?php echo $this->form()->closeTag() ?>
<div class="messages">
    <p>Forgot your password? <a href="/forgot_password">Retrieve it</a></p>
    <p>Need an account? <a href="/signup">Sign Up</a></p>
</div>